#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Agrin.MonoAndroid.UI.Resource", IsApplication=true)]

namespace Agrin.MonoAndroid.UI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class AboutPage
		{
			
			// aapt resource value: 0x7f070000
			public const int ReverceLinearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int ReverceLinearLayout2 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int ReverceLinearLayout3 = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int TxtMessage = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int TxtProgrammer = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int TxtProgrammerTitle = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int TxtSite = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int TxtSiteTitle = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int TxtVersion = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int TxtVersionTitle = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int btnCheckManualVersion = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int btnLearning = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int btnSendFeedBack = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int chkCheckLastVesrion = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int chkGetApplicationMessage = 2131165198;
			
			static AboutPage()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private AboutPage()
			{
			}
		}
		
		public partial class AddGroups
		{
			
			// aapt resource value: 0x7f080008
			public const int LinearLayoutReverce1 = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int LinearLayoutRightToLeft = 2131230720;
			
			// aapt resource value: 0x7f080009
			public const int btnAdd = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int btnBrowse = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int btnCancel = 2131230730;
			
			// aapt resource value: 0x7f080003
			public const int txt_AddressTitle = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int txt_Extentions = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int txt_ExtentionsTitle = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int txt_Name = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int txt_NameTitle = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int txt_SavePath = 2131230724;
			
			static AddGroups()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private AddGroups()
			{
			}
		}
		
		public partial class AddLinks
		{
			
			// aapt resource value: 0x7f090002
			public const int LinearLayoutReverce1 = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int LinearLayoutReverce2 = 2131296267;
			
			// aapt resource value: 0x7f090000
			public const int LinearLayoutRightToLeft = 2131296256;
			
			// aapt resource value: 0x7f09000c
			public const int btnAdd = 2131296268;
			
			// aapt resource value: 0x7f09000a
			public const int btnAddUserAuthorization = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int btnBrowse = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public const int btnCancel = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int btnPlay = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int btnUploadToServer = 2131296271;
			
			// aapt resource value: 0x7f090004
			public const int btn_Extract = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int cboGroups = 2131296262;
			
			// aapt resource value: 0x7f090001
			public const int txtAddressTitle = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int txtGroupNameTitle = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int txtSavePathTitle = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int txt_Address = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int txt_SavePath = 2131296264;
			
			static AddLinks()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private AddLinks()
			{
			}
		}
		
		public partial class AddYoutubeLink
		{
			
			// aapt resource value: 0x7f0a0002
			public const int LinearLayoutReverce1 = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int LinearLayoutRightToLeft = 2131361792;
			
			// aapt resource value: 0x7f0a0005
			public const int btnFindVideo = 2131361797;
			
			// aapt resource value: 0x7f0a0008
			public const int btnSelect = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int btnUploadToServer = 2131361801;
			
			// aapt resource value: 0x7f0a0004
			public const int btn_Extract = 2131361796;
			
			// aapt resource value: 0x7f0a0007
			public const int cboFormats = 2131361799;
			
			// aapt resource value: 0x7f0a0001
			public const int txtAddressTitle = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int txtVideoFormatTitle = 2131361798;
			
			// aapt resource value: 0x7f0a0003
			public const int txt_Address = 2131361795;
			
			static AddYoutubeLink()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private AddYoutubeLink()
			{
			}
		}
		
		public partial class AppSetting
		{
			
			// aapt resource value: 0x7f0b000d
			public const int LinearLayoutReverce1 = 2131427341;
			
			// aapt resource value: 0x7f0b0000
			public const int LinearLayoutRightToLeft = 2131427328;
			
			// aapt resource value: 0x7f0b000f
			public const int btnCancel = 2131427343;
			
			// aapt resource value: 0x7f0b000e
			public const int btnSaveSetting = 2131427342;
			
			// aapt resource value: 0x7f0b000b
			public const int btnSelectLanguage = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int btnUserAuthorization = 2131427340;
			
			// aapt resource value: 0x7f0b0003
			public const int btn_browseDownloadsPath = 2131427331;
			
			// aapt resource value: 0x7f0b000a
			public const int chkEnableNotifyTitle = 2131427338;
			
			// aapt resource value: 0x7f0b0007
			public const int chkIsLimitTitle = 2131427335;
			
			// aapt resource value: 0x7f0b0005
			public const int seekBarConnectionCount = 2131427333;
			
			// aapt resource value: 0x7f0b0008
			public const int seekBarLimit = 2131427336;
			
			// aapt resource value: 0x7f0b0006
			public const int txtConnectionCount = 2131427334;
			
			// aapt resource value: 0x7f0b0004
			public const int txtConnectionCountTitle = 2131427332;
			
			// aapt resource value: 0x7f0b0001
			public const int txtDownloadsPathTitle = 2131427329;
			
			// aapt resource value: 0x7f0b0009
			public const int txtLimit = 2131427337;
			
			// aapt resource value: 0x7f0b0002
			public const int txt_DownloadsPath = 2131427330;
			
			static AppSetting()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private AppSetting()
			{
			}
		}
		
		public partial class ApplicationLog
		{
			
			// aapt resource value: 0x7f190000
			public const int TxTmessageBox = 2132344832;
			
			// aapt resource value: 0x7f190001
			public const int btn_All = 2132344833;
			
			// aapt resource value: 0x7f190003
			public const int btn_ClearLogs = 2132344835;
			
			// aapt resource value: 0x7f190002
			public const int btn_ErrorLogs = 2132344834;
			
			static ApplicationLog()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private ApplicationLog()
			{
			}
		}
		
		public partial class ComboBoxItem
		{
			
			// aapt resource value: 0x7f0c0000
			public const int txtDisplayText = 2131492864;
			
			static ComboBoxItem()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private ComboBoxItem()
			{
			}
		}
		
		public partial class ConnectionInfoListItem
		{
			
			// aapt resource value: 0x7f0d0001
			public const int LinearLayoutRightToLeft1 = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int LinearLayoutRightToLeft2 = 2131558402;
			
			// aapt resource value: 0x7f0d0000
			public const int mainLayout = 2131558400;
			
			// aapt resource value: 0x7f0d0006
			public const int mainProgress = 2131558406;
			
			// aapt resource value: 0x7f0d0005
			public const int txtDownloaded = 2131558405;
			
			// aapt resource value: 0x7f0d0004
			public const int txtSize = 2131558404;
			
			// aapt resource value: 0x7f0d0003
			public const int txtStatus = 2131558403;
			
			static ConnectionInfoListItem()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private ConnectionInfoListItem()
			{
			}
		}
		
		public partial class FolderBrowserDialog
		{
			
			// aapt resource value: 0x7f0e0000
			public const int LinearLayoutReverce1 = 2131623936;
			
			// aapt resource value: 0x7f0e0004
			public const int LinearLayoutReverce2 = 2131623940;
			
			// aapt resource value: 0x7f0e0007
			public const int btnBack = 2131623943;
			
			// aapt resource value: 0x7f0e0008
			public const int btnCancel = 2131623944;
			
			// aapt resource value: 0x7f0e0002
			public const int btnGo = 2131623938;
			
			// aapt resource value: 0x7f0e0006
			public const int btnNewFolder = 2131623942;
			
			// aapt resource value: 0x7f0e0005
			public const int btnSelect = 2131623941;
			
			// aapt resource value: 0x7f0e0003
			public const int mainGridView = 2131623939;
			
			// aapt resource value: 0x7f0e0001
			public const int txt_GoPath = 2131623937;
			
			static FolderBrowserDialog()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private FolderBrowserDialog()
			{
			}
		}
		
		public partial class FolderInfoItem
		{
			
			// aapt resource value: 0x7f0f0000
			public const int imgIcon = 2131689472;
			
			// aapt resource value: 0x7f0f0001
			public const int txtName = 2131689473;
			
			static FolderInfoItem()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private FolderInfoItem()
			{
			}
		}
		
		public partial class FramesoftLinksListData
		{
			
			// aapt resource value: 0x7f100002
			public const int btnRefersh = 2131755010;
			
			// aapt resource value: 0x7f100000
			public const int mainLayout = 2131755008;
			
			// aapt resource value: 0x7f100001
			public const int mainListView = 2131755009;
			
			static FramesoftLinksListData()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private FramesoftLinksListData()
			{
			}
		}
		
		public partial class GroupListData
		{
			
			// aapt resource value: 0x7f110002
			public const int LinearLayoutReverce1 = 2131820546;
			
			// aapt resource value: 0x7f110003
			public const int btnAddGroup = 2131820547;
			
			// aapt resource value: 0x7f110004
			public const int btnDelete = 2131820548;
			
			// aapt resource value: 0x7f110000
			public const int mainLayout = 2131820544;
			
			// aapt resource value: 0x7f110001
			public const int mainListView = 2131820545;
			
			static GroupListData()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private GroupListData()
			{
			}
		}
		
		public partial class GroupListItem
		{
			
			// aapt resource value: 0x7f120000
			public const int mainLayout = 2131886080;
			
			// aapt resource value: 0x7f120001
			public const int txtGroupName = 2131886081;
			
			// aapt resource value: 0x7f120002
			public const int txtSaveAddress = 2131886082;
			
			static GroupListItem()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private GroupListItem()
			{
			}
		}
		
		public partial class LanguageSetting
		{
			
			// aapt resource value: 0x7f130001
			public const int btnEnglish = 2131951617;
			
			// aapt resource value: 0x7f130000
			public const int btnPersian = 2131951616;
			
			static LanguageSetting()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private LanguageSetting()
			{
			}
		}
		
		public partial class LinkInfoDownloadDetail
		{
			
			// aapt resource value: 0x7f140002
			public const int LinearLayoutReverce1 = 2132017154;
			
			// aapt resource value: 0x7f140006
			public const int LinearLayoutReverce2 = 2132017158;
			
			// aapt resource value: 0x7f14000a
			public const int LinearLayoutReverce3 = 2132017162;
			
			// aapt resource value: 0x7f14000e
			public const int LinearLayoutReverce4 = 2132017166;
			
			// aapt resource value: 0x7f140012
			public const int LinearLayoutReverce5 = 2132017170;
			
			// aapt resource value: 0x7f140016
			public const int LinearLayoutReverce6 = 2132017174;
			
			// aapt resource value: 0x7f14001b
			public const int LinearLayoutReverce7 = 2132017179;
			
			// aapt resource value: 0x7f140003
			public const int LinearLayoutRightToLeft1 = 2132017155;
			
			// aapt resource value: 0x7f140007
			public const int LinearLayoutRightToLeft2 = 2132017159;
			
			// aapt resource value: 0x7f14000b
			public const int LinearLayoutRightToLeft3 = 2132017163;
			
			// aapt resource value: 0x7f14000f
			public const int LinearLayoutRightToLeft4 = 2132017167;
			
			// aapt resource value: 0x7f140013
			public const int LinearLayoutRightToLeft5 = 2132017171;
			
			// aapt resource value: 0x7f140017
			public const int LinearLayoutRightToLeft7 = 2132017175;
			
			// aapt resource value: 0x7f14001c
			public const int btnPlay = 2132017180;
			
			// aapt resource value: 0x7f14001d
			public const int btnReConnect = 2132017181;
			
			// aapt resource value: 0x7f14001e
			public const int btnStop = 2132017182;
			
			// aapt resource value: 0x7f140000
			public const int mainLayout = 2132017152;
			
			// aapt resource value: 0x7f14001f
			public const int mainList = 2132017183;
			
			// aapt resource value: 0x7f14000d
			public const int txtDownloadedSize = 2132017165;
			
			// aapt resource value: 0x7f14000c
			public const int txtDownloadedSizeTitle = 2132017164;
			
			// aapt resource value: 0x7f140001
			public const int txtFileName = 2132017153;
			
			// aapt resource value: 0x7f14001a
			public const int txtPerSecound = 2132017178;
			
			// aapt resource value: 0x7f140011
			public const int txtResumable = 2132017169;
			
			// aapt resource value: 0x7f140010
			public const int txtResumableTitle = 2132017168;
			
			// aapt resource value: 0x7f140009
			public const int txtSize = 2132017161;
			
			// aapt resource value: 0x7f140008
			public const int txtSizeTitle = 2132017160;
			
			// aapt resource value: 0x7f140019
			public const int txtSpeed = 2132017177;
			
			// aapt resource value: 0x7f140018
			public const int txtSpeedTitle = 2132017176;
			
			// aapt resource value: 0x7f140005
			public const int txtStatus = 2132017157;
			
			// aapt resource value: 0x7f140004
			public const int txtStatusTitle = 2132017156;
			
			// aapt resource value: 0x7f140015
			public const int txtTimeRemainig = 2132017173;
			
			// aapt resource value: 0x7f140014
			public const int txtTimeRemainingTitle = 2132017172;
			
			static LinkInfoDownloadDetail()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private LinkInfoDownloadDetail()
			{
			}
		}
		
		public partial class LinkInfoPropertiesGeneral
		{
			
			// aapt resource value: 0x7f150004
			public const int LinearLayoutReverce1 = 2132082692;
			
			// aapt resource value: 0x7f150000
			public const int LinearLayoutRightToLeft = 2132082688;
			
			// aapt resource value: 0x7f150006
			public const int btnCancel = 2132082694;
			
			// aapt resource value: 0x7f150005
			public const int btnSaveSetting = 2132082693;
			
			// aapt resource value: 0x7f150003
			public const int btn_browseSaveLinkPath = 2132082691;
			
			// aapt resource value: 0x7f150001
			public const int txtSaveLinkPathTitle = 2132082689;
			
			// aapt resource value: 0x7f150002
			public const int txt_SaveLinkPath = 2132082690;
			
			static LinkInfoPropertiesGeneral()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private LinkInfoPropertiesGeneral()
			{
			}
		}
		
		public partial class LinkInfoPropertiesLinks
		{
			
			// aapt resource value: 0x7f160000
			public const int LinearLayoutRightToLeft = 2132148224;
			
			// aapt resource value: 0x7f160001
			public const int asasdasdad = 2132148225;
			
			static LinkInfoPropertiesLinks()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private LinkInfoPropertiesLinks()
			{
			}
		}
		
		public partial class LinksListData
		{
			
			// aapt resource value: 0x7f170002
			public const int LinearLayoutReverce1 = 2132213762;
			
			// aapt resource value: 0x7f170006
			public const int LinearLayoutReverce2 = 2132213766;
			
			// aapt resource value: 0x7f170009
			public const int LinearLayoutReverce3 = 2132213769;
			
			// aapt resource value: 0x7f170005
			public const int btnDelete = 2132213765;
			
			// aapt resource value: 0x7f170008
			public const int btnDeleteComplete = 2132213768;
			
			// aapt resource value: 0x7f17000a
			public const int btnDownloadQueue = 2132213770;
			
			// aapt resource value: 0x7f170003
			public const int btnPlay = 2132213763;
			
			// aapt resource value: 0x7f170007
			public const int btnSelectAll = 2132213767;
			
			// aapt resource value: 0x7f170004
			public const int btnStop = 2132213764;
			
			// aapt resource value: 0x7f170000
			public const int mainLayout = 2132213760;
			
			// aapt resource value: 0x7f170001
			public const int mainListView = 2132213761;
			
			static LinksListData()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private LinksListData()
			{
			}
		}
		
		public partial class ListLinkItem
		{
			
			// aapt resource value: 0x7f180002
			public const int chkFileName = 2132279298;
			
			// aapt resource value: 0x7f180000
			public const int mainLayout = 2132279296;
			
			// aapt resource value: 0x7f180004
			public const int mainProgress = 2132279300;
			
			// aapt resource value: 0x7f180001
			public const int selectLayout = 2132279297;
			
			// aapt resource value: 0x7f180003
			public const int txtData = 2132279299;
			
			static ListLinkItem()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private ListLinkItem()
			{
			}
		}
		
		public partial class NotifyLinkDownloading
		{
			
			// aapt resource value: 0x7f1b0002
			public const int chkFileName = 2132475906;
			
			// aapt resource value: 0x7f1b0000
			public const int mainLayout = 2132475904;
			
			// aapt resource value: 0x7f1b0005
			public const int mainProgress = 2132475909;
			
			// aapt resource value: 0x7f1b0001
			public const int selectLayout = 2132475905;
			
			// aapt resource value: 0x7f1b0006
			public const int txtPercentData = 2132475910;
			
			// aapt resource value: 0x7f1b0003
			public const int txtSizeData = 2132475907;
			
			// aapt resource value: 0x7f1b0004
			public const int txtStateData = 2132475908;
			
			static NotifyLinkDownloading()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private NotifyLinkDownloading()
			{
			}
		}
		
		public partial class QueueSetting
		{
			
			// aapt resource value: 0x7f1c0001
			public const int LinearLayoutReverce1 = 2132541441;
			
			// aapt resource value: 0x7f1c0005
			public const int LinearLayoutReverce2 = 2132541445;
			
			// aapt resource value: 0x7f1c000c
			public const int LinearLayoutReverce3 = 2132541452;
			
			// aapt resource value: 0x7f1c000f
			public const int LinearLayoutReverce4 = 2132541455;
			
			// aapt resource value: 0x7f1c0007
			public const int btnEndtime = 2132541447;
			
			// aapt resource value: 0x7f1c0003
			public const int btnStartTime = 2132541443;
			
			// aapt resource value: 0x7f1c0012
			public const int btn_Cancel = 2132541458;
			
			// aapt resource value: 0x7f1c0010
			public const int btn_SaveRun = 2132541456;
			
			// aapt resource value: 0x7f1c0011
			public const int btn_Stop = 2132541457;
			
			// aapt resource value: 0x7f1c0000
			public const int chkStartNow = 2132541440;
			
			// aapt resource value: 0x7f1c0004
			public const int chkTryExterme = 2132541444;
			
			// aapt resource value: 0x7f1c000b
			public const int chkTurnOffDataComplete = 2132541451;
			
			// aapt resource value: 0x7f1c0009
			public const int chkTurnOffWifiComplete = 2132541449;
			
			// aapt resource value: 0x7f1c000a
			public const int chkTurnOnDataStart = 2132541450;
			
			// aapt resource value: 0x7f1c0008
			public const int chkTurnOnWifiStart = 2132541448;
			
			// aapt resource value: 0x7f1c000d
			public const int txtDownloadCountTitle = 2132541453;
			
			// aapt resource value: 0x7f1c0002
			public const int txtStartTimeTitle = 2132541442;
			
			// aapt resource value: 0x7f1c0006
			public const int txtTitleEndTime = 2132541446;
			
			// aapt resource value: 0x7f1c000e
			public const int txt_DownloadCount = 2132541454;
			
			static QueueSetting()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private QueueSetting()
			{
			}
		}
		
		public partial class RepairLink
		{
			
			// aapt resource value: 0x7f1d0002
			public const int mainProgress = 2132606978;
			
			// aapt resource value: 0x7f1d0001
			public const int stageProgress = 2132606977;
			
			// aapt resource value: 0x7f1d0000
			public const int txtState = 2132606976;
			
			static RepairLink()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private RepairLink()
			{
			}
		}
		
		public partial class Toolbars
		{
			
			// aapt resource value: 0x7f1e0006
			public const int btnAbout = 2132672518;
			
			// aapt resource value: 0x7f1e0008
			public const int btnGoToHome = 2132672520;
			
			// aapt resource value: 0x7f1e0007
			public const int btnVIP = 2132672519;
			
			// aapt resource value: 0x7f1e0001
			public const int btn_AddLinks = 2132672513;
			
			// aapt resource value: 0x7f1e0002
			public const int btn_AddYoutubeLinks = 2132672514;
			
			// aapt resource value: 0x7f1e0003
			public const int btn_GroupManager = 2132672515;
			
			// aapt resource value: 0x7f1e0000
			public const int btn_Links = 2132672512;
			
			// aapt resource value: 0x7f1e0004
			public const int btn_Setting = 2132672516;
			
			// aapt resource value: 0x7f1e0005
			public const int btn_applicationLog = 2132672517;
			
			static Toolbars()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Toolbars()
			{
			}
		}
		
		public partial class UserAuthorizationList
		{
			
			// aapt resource value: 0x7f1f0002
			public const int LinearLayoutReverce1 = 2132738050;
			
			// aapt resource value: 0x7f1f0003
			public const int btnAddUserAuthorization = 2132738051;
			
			// aapt resource value: 0x7f1f0004
			public const int btnDelete = 2132738052;
			
			// aapt resource value: 0x7f1f0000
			public const int mainLayout = 2132738048;
			
			// aapt resource value: 0x7f1f0001
			public const int mainListView = 2132738049;
			
			static UserAuthorizationList()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private UserAuthorizationList()
			{
			}
		}
		
		public partial class VIPToolbar
		{
			
			// aapt resource value: 0x7f200006
			public const int ReverceLinearLayout1 = 2132803590;
			
			// aapt resource value: 0x7f200009
			public const int ReverceLinearLayout2 = 2132803593;
			
			// aapt resource value: 0x7f200001
			public const int btn_BuyStorage = 2132803585;
			
			// aapt resource value: 0x7f200000
			public const int btn_Downloads = 2132803584;
			
			// aapt resource value: 0x7f200004
			public const int btn_Login = 2132803588;
			
			// aapt resource value: 0x7f200005
			public const int btn_Logout = 2132803589;
			
			// aapt resource value: 0x7f200003
			public const int btn_Register = 2132803587;
			
			// aapt resource value: 0x7f200002
			public const int btn_UserPermission = 2132803586;
			
			// aapt resource value: 0x7f20000b
			public const int txtSize = 2132803595;
			
			// aapt resource value: 0x7f20000a
			public const int txtSizeTitle = 2132803594;
			
			// aapt resource value: 0x7f200008
			public const int txtUserName = 2132803592;
			
			// aapt resource value: 0x7f200007
			public const int txtUserNameTitle = 2132803591;
			
			static VIPToolbar()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private VIPToolbar()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int cellback = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int custom_progressbar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Mydocumentsicon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int smallIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splashscreen = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ViewCellBackground = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int WhiteIcon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f1a0000
			public const int linearLayout1 = 2132410368;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddGroup = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddLink = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AddUserAuthorization = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AddYoutubeLink = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AppSetting = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ComboBoxItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ConnectionInfoListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int FolderBrowserDialog = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int FolderInfoItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int FramesoftLinksListData = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int GroupListData = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int GroupListItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LanguageSetting = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int LinkInfoDownloadDetail = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int LinkInfoProperties = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int LinkInfoPropertiesGeneral = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int LinkInfoPropertiesLinks = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int LinksListData = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int LinksListItem = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int MessageBox = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int NotifyLinkDownloading = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int QueueSetting = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int RepairLink = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Toolbar = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int UserAuthorizationList = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int VIPToolbar = 2130903066;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040170
			public const int AboutLearning_Language_en = 2130968944;
			
			// aapt resource value: 0x7f04002e
			public const int AboutLearning_Language_fa = 2130968622;
			
			// aapt resource value: 0x7f040169
			public const int AboutQuestion2_Language_en = 2130968937;
			
			// aapt resource value: 0x7f04002d
			public const int AboutQuestion2_Language_fa = 2130968621;
			
			// aapt resource value: 0x7f040168
			public const int AboutQuestion_Language_en = 2130968936;
			
			// aapt resource value: 0x7f04002c
			public const int AboutQuestion_Language_fa = 2130968620;
			
			// aapt resource value: 0x7f0400fe
			public const int About_Language_en = 2130968830;
			
			// aapt resource value: 0x7f040012
			public const int About_Language_fa = 2130968594;
			
			// aapt resource value: 0x7f040102
			public const int AddGroup_Language_en = 2130968834;
			
			// aapt resource value: 0x7f040016
			public const int AddGroup_Language_fa = 2130968598;
			
			// aapt resource value: 0x7f040106
			public const int AddLink_Language_en = 2130968838;
			
			// aapt resource value: 0x7f04001a
			public const int AddLink_Language_fa = 2130968602;
			
			// aapt resource value: 0x7f040159
			public const int AddUserAuthorization_Language_en = 2130968921;
			
			// aapt resource value: 0x7f040086
			public const int AddUserAuthorization_Language_fa = 2130968710;
			
			// aapt resource value: 0x7f04010a
			public const int AddYoutubeLink_Language_en = 2130968842;
			
			// aapt resource value: 0x7f04001e
			public const int AddYoutubeLink_Language_fa = 2130968606;
			
			// aapt resource value: 0x7f0400f2
			public const int Add_Language_en = 2130968818;
			
			// aapt resource value: 0x7f040006
			public const int Add_Language_fa = 2130968582;
			
			// aapt resource value: 0x7f040199
			public const int AgreePermissions_Language_en = 2130968985;
			
			// aapt resource value: 0x7f0400b0
			public const int AgreePermissions_Language_fa = 2130968752;
			
			// aapt resource value: 0x7f040164
			public const int AgrinApplicationMessageMessage_Language_en = 2130968932;
			
			// aapt resource value: 0x7f040028
			public const int AgrinApplicationMessageMessage_Language_fa = 2130968616;
			
			// aapt resource value: 0x7f040163
			public const int AgrinApplicationMessageTitle_Language_en = 2130968931;
			
			// aapt resource value: 0x7f040025
			public const int AgrinApplicationMessageTitle_Language_fa = 2130968613;
			
			// aapt resource value: 0x7f040166
			public const int AgrinApplicationNewVersionMessage_Language_en = 2130968934;
			
			// aapt resource value: 0x7f04002a
			public const int AgrinApplicationNewVersionMessage_Language_fa = 2130968618;
			
			// aapt resource value: 0x7f040165
			public const int AgrinApplicationNewVersionTitle_Language_en = 2130968933;
			
			// aapt resource value: 0x7f040029
			public const int AgrinApplicationNewVersionTitle_Language_fa = 2130968617;
			
			// aapt resource value: 0x7f040167
			public const int AgrinApplicationUserMessageTitle_Language_en = 2130968935;
			
			// aapt resource value: 0x7f04002b
			public const int AgrinApplicationUserMessageTitle_Language_fa = 2130968619;
			
			// aapt resource value: 0x7f040110
			public const int AgrinDownloadManager_Language_en = 2130968848;
			
			// aapt resource value: 0x7f040024
			public const int AgrinDownloadManager_Language_fa = 2130968612;
			
			// aapt resource value: 0x7f040140
			public const int And_Language_en = 2130968896;
			
			// aapt resource value: 0x7f04006a
			public const int And_Language_fa = 2130968682;
			
			// aapt resource value: 0x7f040155
			public const int AppSetting_Language_en = 2130968917;
			
			// aapt resource value: 0x7f040082
			public const int AppSetting_Language_fa = 2130968706;
			
			// aapt resource value: 0x7f040118
			public const int ApplicationIsDownloading_Language_en = 2130968856;
			
			// aapt resource value: 0x7f040041
			public const int ApplicationIsDownloading_Language_fa = 2130968641;
			
			// aapt resource value: 0x7f04014f
			public const int ApplicationLogs_Language_en = 2130968911;
			
			// aapt resource value: 0x7f040079
			public const int ApplicationLogs_Language_fa = 2130968697;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04015e
			public const int AreyousureyouwanttodeleteselectedItems_Language_en = 2130968926;
			
			// aapt resource value: 0x7f04008b
			public const int AreyousureyouwanttodeleteselectedItems_Language_fa = 2130968715;
			
			// aapt resource value: 0x7f040115
			public const int Areyousureyouwanttodeleteselectedgroups_Language_en = 2130968853;
			
			// aapt resource value: 0x7f04003d
			public const int Areyousureyouwanttodeleteselectedgroups_Language_fa = 2130968637;
			
			// aapt resource value: 0x7f040116
			public const int Areyousureyouwanttodeleteselectedlinks_Language_en = 2130968854;
			
			// aapt resource value: 0x7f04003e
			public const int Areyousureyouwanttodeleteselectedlinks_Language_fa = 2130968638;
			
			// aapt resource value: 0x7f04014e
			public const int Back_Language_en = 2130968910;
			
			// aapt resource value: 0x7f040078
			public const int Back_Language_fa = 2130968696;
			
			// aapt resource value: 0x7f040122
			public const int BrokenLink_Language_en = 2130968866;
			
			// aapt resource value: 0x7f04004a
			public const int BrokenLink_Language_fa = 2130968650;
			
			// aapt resource value: 0x7f04014b
			public const int BrowseFolder_Language_en = 2130968907;
			
			// aapt resource value: 0x7f040075
			public const int BrowseFolder_Language_fa = 2130968693;
			
			// aapt resource value: 0x7f040149
			public const int Browse_Language_en = 2130968905;
			
			// aapt resource value: 0x7f040073
			public const int Browse_Language_fa = 2130968691;
			
			// aapt resource value: 0x7f0401b6
			public const int BuyPurchaseError_Language_en = 2130969014;
			
			// aapt resource value: 0x7f0400cd
			public const int BuyPurchaseError_Language_fa = 2130968781;
			
			// aapt resource value: 0x7f0401b4
			public const int BuyPurchase_Language_en = 2130969012;
			
			// aapt resource value: 0x7f0400cb
			public const int BuyPurchase_Language_fa = 2130968779;
			
			// aapt resource value: 0x7f0401b7
			public const int BuyStorageSuccess_Language_en = 2130969015;
			
			// aapt resource value: 0x7f0400ce
			public const int BuyStorageSuccess_Language_fa = 2130968782;
			
			// aapt resource value: 0x7f0401a0
			public const int BuyStorage_Language_en = 2130968992;
			
			// aapt resource value: 0x7f0400b7
			public const int BuyStorage_Language_fa = 2130968759;
			
			// aapt resource value: 0x7f0401b5
			public const int BuyingPurchase_Language_en = 2130969013;
			
			// aapt resource value: 0x7f0400cc
			public const int BuyingPurchase_Language_fa = 2130968780;
			
			// aapt resource value: 0x7f040131
			public const int Byte_Language_en = 2130968881;
			
			// aapt resource value: 0x7f04005b
			public const int Byte_Language_fa = 2130968667;
			
			// aapt resource value: 0x7f0401c4
			public const int CafeBazaarErrorConnection_Language_en = 2130969028;
			
			// aapt resource value: 0x7f0400db
			public const int CafeBazaarErrorConnection_Language_fa = 2130968795;
			
			// aapt resource value: 0x7f0400f4
			public const int Cancel_Language_en = 2130968820;
			
			// aapt resource value: 0x7f040008
			public const int Cancel_Language_fa = 2130968584;
			
			// aapt resource value: 0x7f0401d2
			public const int CannotDownload_Language_en = 2130969042;
			
			// aapt resource value: 0x7f0400e9
			public const int CannotDownload_Language_fa = 2130968809;
			
			// aapt resource value: 0x7f040184
			public const int ChangeFileLocation_Language_en = 2130968964;
			
			// aapt resource value: 0x7f04003b
			public const int ChangeFileLocation_Language_fa = 2130968635;
			
			// aapt resource value: 0x7f04017b
			public const int ChangeLinkAddress_Language_en = 2130968955;
			
			// aapt resource value: 0x7f04009a
			public const int ChangeLinkAddress_Language_fa = 2130968730;
			
			// aapt resource value: 0x7f040176
			public const int CheckCompleteMessageYouInNotification_Language_en = 2130968950;
			
			// aapt resource value: 0x7f040095
			public const int CheckCompleteMessageYouInNotification_Language_fa = 2130968725;
			
			// aapt resource value: 0x7f04017a
			public const int CheckForGetApplicationMessage_Language_en = 2130968954;
			
			// aapt resource value: 0x7f040099
			public const int CheckForGetApplicationMessage_Language_fa = 2130968729;
			
			// aapt resource value: 0x7f040123
			public const int CheckForSupportResumable_Language_en = 2130968867;
			
			// aapt resource value: 0x7f04004b
			public const int CheckForSupportResumable_Language_fa = 2130968651;
			
			// aapt resource value: 0x7f040179
			public const int CheckForUpdateAutomatic_Language_en = 2130968953;
			
			// aapt resource value: 0x7f040098
			public const int CheckForUpdateAutomatic_Language_fa = 2130968728;
			
			// aapt resource value: 0x7f040178
			public const int CheckForUpdate_Language_en = 2130968952;
			
			// aapt resource value: 0x7f040097
			public const int CheckForUpdate_Language_fa = 2130968727;
			
			// aapt resource value: 0x7f040175
			public const int Checking_Language_en = 2130968949;
			
			// aapt resource value: 0x7f040094
			public const int Checking_Language_fa = 2130968724;
			
			// aapt resource value: 0x7f040161
			public const int CompleteDownloadNotify_Language_en = 2130968929;
			
			// aapt resource value: 0x7f04008e
			public const int CompleteDownloadNotify_Language_fa = 2130968718;
			
			// aapt resource value: 0x7f04018d
			public const int CompleteFileForRepairNotFound_Language_en = 2130968973;
			
			// aapt resource value: 0x7f0400a6
			public const int CompleteFileForRepairNotFound_Language_fa = 2130968742;
			
			// aapt resource value: 0x7f04011e
			public const int Complete_Language_en = 2130968862;
			
			// aapt resource value: 0x7f040046
			public const int Complete_Language_fa = 2130968646;
			
			// aapt resource value: 0x7f040127
			public const int ConnectingToSharing_Language_en = 2130968871;
			
			// aapt resource value: 0x7f04004f
			public const int ConnectingToSharing_Language_fa = 2130968655;
			
			// aapt resource value: 0x7f040121
			public const int Connecting_Language_en = 2130968865;
			
			// aapt resource value: 0x7f040049
			public const int Connecting_Language_fa = 2130968649;
			
			// aapt resource value: 0x7f04018b
			public const int CopyLinkAddress_Language_en = 2130968971;
			
			// aapt resource value: 0x7f0400a4
			public const int CopyLinkAddress_Language_fa = 2130968740;
			
			// aapt resource value: 0x7f040124
			public const int CopyingFile_Language_en = 2130968868;
			
			// aapt resource value: 0x7f04004c
			public const int CopyingFile_Language_fa = 2130968652;
			
			// aapt resource value: 0x7f040112
			public const int CouldNotOpenThisFile_Language_en = 2130968850;
			
			// aapt resource value: 0x7f040036
			public const int CouldNotOpenThisFile_Language_fa = 2130968630;
			
			// aapt resource value: 0x7f040182
			public const int CouldNotOpenThisLocation_Language_en = 2130968962;
			
			// aapt resource value: 0x7f04003a
			public const int CouldNotOpenThisLocation_Language_fa = 2130968634;
			
			// aapt resource value: 0x7f04007a
			public const int CreateFolderTitle_Language_fa = 2130968698;
			
			// aapt resource value: 0x7f04011a
			public const int CreatingRequest_Language_en = 2130968858;
			
			// aapt resource value: 0x7f04003f
			public const int CreatingRequest_Language_fa = 2130968639;
			
			// aapt resource value: 0x7f04013f
			public const int Day_Language_en = 2130968895;
			
			// aapt resource value: 0x7f040069
			public const int Day_Language_fa = 2130968681;
			
			// aapt resource value: 0x7f0400f7
			public const int DeleteComplete_Language_en = 2130968823;
			
			// aapt resource value: 0x7f04000b
			public const int DeleteComplete_Language_fa = 2130968587;
			
			// aapt resource value: 0x7f0401c5
			public const int DeleteFilesFromServer_Language_en = 2130969029;
			
			// aapt resource value: 0x7f0400dc
			public const int DeleteFilesFromServer_Language_fa = 2130968796;
			
			// aapt resource value: 0x7f0401ba
			public const int DeleteFromServer_Language_en = 2130969018;
			
			// aapt resource value: 0x7f0400d1
			public const int DeleteFromServer_Language_fa = 2130968785;
			
			// aapt resource value: 0x7f0400f5
			public const int Delete_Language_en = 2130968821;
			
			// aapt resource value: 0x7f040009
			public const int Delete_Language_fa = 2130968585;
			
			// aapt resource value: 0x7f0401c7
			public const int DeletingFilesError_Language_en = 2130969031;
			
			// aapt resource value: 0x7f0400de
			public const int DeletingFilesError_Language_fa = 2130968798;
			
			// aapt resource value: 0x7f0401c6
			public const int DeletingFilesFromServer_Language_en = 2130969030;
			
			// aapt resource value: 0x7f0400dd
			public const int DeletingFilesFromServer_Language_fa = 2130968797;
			
			// aapt resource value: 0x7f0400fa
			public const int DeveloperTitle_Language_en = 2130968826;
			
			// aapt resource value: 0x7f04000e
			public const int DeveloperTitle_Language_fa = 2130968590;
			
			// aapt resource value: 0x7f0400f9
			public const int Developer_Language_en = 2130968825;
			
			// aapt resource value: 0x7f04000d
			public const int Developer_Language_fa = 2130968589;
			
			// aapt resource value: 0x7f040126
			public const int Disposed_Language_en = 2130968870;
			
			// aapt resource value: 0x7f04004e
			public const int Disposed_Language_fa = 2130968654;
			
			// aapt resource value: 0x7f040188
			public const int DoYouDownloadQueueList_Language_en = 2130968968;
			
			// aapt resource value: 0x7f0400a1
			public const int DoYouDownloadQueueList_Language_fa = 2130968737;
			
			// aapt resource value: 0x7f040189
			public const int DoYouWantToStopDownloadQueueList_Language_en = 2130968969;
			
			// aapt resource value: 0x7f0400a2
			public const int DoYouWantToStopDownloadQueueList_Language_fa = 2130968738;
			
			// aapt resource value: 0x7f040187
			public const int DownloadQueueList_Language_en = 2130968967;
			
			// aapt resource value: 0x7f0400a0
			public const int DownloadQueueList_Language_fa = 2130968736;
			
			// aapt resource value: 0x7f0401b9
			public const int Download_Language_en = 2130969017;
			
			// aapt resource value: 0x7f0400d0
			public const int Download_Language_fa = 2130968784;
			
			// aapt resource value: 0x7f040138
			public const int Downloaded_Language_en = 2130968888;
			
			// aapt resource value: 0x7f040062
			public const int Downloaded_Language_fa = 2130968674;
			
			// aapt resource value: 0x7f040191
			public const int DownloadingProblems_Language_en = 2130968977;
			
			// aapt resource value: 0x7f0400aa
			public const int DownloadingProblems_Language_fa = 2130968746;
			
			// aapt resource value: 0x7f040119
			public const int Downloading_Language_en = 2130968857;
			
			// aapt resource value: 0x7f040042
			public const int Downloading_Language_fa = 2130968642;
			
			// aapt resource value: 0x7f04010b
			public const int DownloadsLink_Language_en = 2130968843;
			
			// aapt resource value: 0x7f04001f
			public const int DownloadsLink_Language_fa = 2130968607;
			
			// aapt resource value: 0x7f040150
			public const int DownloadsPathTitle_Language_en = 2130968912;
			
			// aapt resource value: 0x7f04007d
			public const int DownloadsPathTitle_Language_fa = 2130968701;
			
			// aapt resource value: 0x7f04010c
			public const int Downloads_Language_en = 2130968844;
			
			// aapt resource value: 0x7f040020
			public const int Downloads_Language_fa = 2130968608;
			
			// aapt resource value: 0x7f040136
			public const int EB_Language_en = 2130968886;
			
			// aapt resource value: 0x7f040060
			public const int EB_Language_fa = 2130968672;
			
			// aapt resource value: 0x7f0401cd
			public const int EmailExist_Language_en = 2130969037;
			
			// aapt resource value: 0x7f0400e4
			public const int EmailExist_Language_fa = 2130968804;
			
			// aapt resource value: 0x7f0401a7
			public const int Email_Language_en = 2130968999;
			
			// aapt resource value: 0x7f0400be
			public const int Email_Language_fa = 2130968766;
			
			// aapt resource value: 0x7f0401aa
			public const int EmptyUserPassEmail_Language_en = 2130969002;
			
			// aapt resource value: 0x7f0400c1
			public const int EmptyUserPassEmail_Language_fa = 2130968769;
			
			// aapt resource value: 0x7f04019d
			public const int EmptyUserPass_Language_en = 2130968989;
			
			// aapt resource value: 0x7f0400b4
			public const int EmptyUserPass_Language_fa = 2130968756;
			
			// aapt resource value: 0x7f04015d
			public const int EmptyValidation_Language_en = 2130968925;
			
			// aapt resource value: 0x7f04008a
			public const int EmptyValidation_Language_fa = 2130968714;
			
			// aapt resource value: 0x7f040162
			public const int EnableNotifyTitle_Language_en = 2130968930;
			
			// aapt resource value: 0x7f04008f
			public const int EnableNotifyTitle_Language_fa = 2130968719;
			
			// aapt resource value: 0x7f040177
			public const int ErrorChecking_Language_en = 2130968951;
			
			// aapt resource value: 0x7f040096
			public const int ErrorChecking_Language_fa = 2130968726;
			
			// aapt resource value: 0x7f04007c
			public const int ErrorCreateFolder_Language_fa = 2130968700;
			
			// aapt resource value: 0x7f040120
			public const int ErrorNotify_Language_en = 2130968864;
			
			// aapt resource value: 0x7f040048
			public const int ErrorNotify_Language_fa = 2130968648;
			
			// aapt resource value: 0x7f040174
			public const int ErrorShareFile_Language_en = 2130968948;
			
			// aapt resource value: 0x7f040093
			public const int ErrorShareFile_Language_fa = 2130968723;
			
			// aapt resource value: 0x7f04011f
			public const int Error_Language_en = 2130968863;
			
			// aapt resource value: 0x7f040047
			public const int Error_Language_fa = 2130968647;
			
			// aapt resource value: 0x7f04014a
			public const int ExitApplicationQuestion_Language_en = 2130968906;
			
			// aapt resource value: 0x7f040074
			public const int ExitApplicationQuestion_Language_fa = 2130968692;
			
			// aapt resource value: 0x7f04010e
			public const int Exit_Language_en = 2130968846;
			
			// aapt resource value: 0x7f040022
			public const int Exit_Language_fa = 2130968610;
			
			// aapt resource value: 0x7f040101
			public const int Extentions_Language_en = 2130968833;
			
			// aapt resource value: 0x7f040015
			public const int Extentions_Language_fa = 2130968597;
			
			// aapt resource value: 0x7f040105
			public const int ExtractUrls_Language_en = 2130968837;
			
			// aapt resource value: 0x7f040019
			public const int ExtractUrls_Language_fa = 2130968601;
			
			// aapt resource value: 0x7f0401ca
			public const int FileNotComplete_Language_en = 2130969034;
			
			// aapt resource value: 0x7f0400e1
			public const int FileNotComplete_Language_fa = 2130968801;
			
			// aapt resource value: 0x7f04012e
			public const int FileNotFound_Language_en = 2130968878;
			
			// aapt resource value: 0x7f040056
			public const int FileNotFound_Language_fa = 2130968662;
			
			// aapt resource value: 0x7f040113
			public const int Filedoesnotexist_Language_en = 2130968851;
			
			// aapt resource value: 0x7f040037
			public const int Filedoesnotexist_Language_fa = 2130968631;
			
			// aapt resource value: 0x7f04018f
			public const int FindConnectionProblems_Language_en = 2130968975;
			
			// aapt resource value: 0x7f0400a8
			public const int FindConnectionProblems_Language_fa = 2130968744;
			
			// aapt resource value: 0x7f040190
			public const int FindPositionOfProblems_Language_en = 2130968976;
			
			// aapt resource value: 0x7f0400a9
			public const int FindPositionOfProblems_Language_fa = 2130968745;
			
			// aapt resource value: 0x7f040107
			public const int FindVideos_Language_en = 2130968839;
			
			// aapt resource value: 0x7f04001b
			public const int FindVideos_Language_fa = 2130968603;
			
			// aapt resource value: 0x7f04012a
			public const int FindingAddressFromSharing_Language_en = 2130968874;
			
			// aapt resource value: 0x7f040052
			public const int FindingAddressFromSharing_Language_fa = 2130968658;
			
			// aapt resource value: 0x7f040198
			public const int FindingYoutubeVideos_Language_en = 2130968984;
			
			// aapt resource value: 0x7f0400af
			public const int FindingYoutubeVideos_Language_fa = 2130968751;
			
			// aapt resource value: 0x7f040192
			public const int FixingProblems_Language_en = 2130968978;
			
			// aapt resource value: 0x7f0400ab
			public const int FixingProblems_Language_fa = 2130968747;
			
			// aapt resource value: 0x7f040181
			public const int Folderdoesnotexist_Language_en = 2130968961;
			
			// aapt resource value: 0x7f040039
			public const int Folderdoesnotexist_Language_fa = 2130968633;
			
			// aapt resource value: 0x7f040134
			public const int GB_Language_en = 2130968884;
			
			// aapt resource value: 0x7f04005e
			public const int GB_Language_fa = 2130968670;
			
			// aapt resource value: 0x7f040129
			public const int GetAddressFromSharing_Language_en = 2130968873;
			
			// aapt resource value: 0x7f040051
			public const int GetAddressFromSharing_Language_fa = 2130968657;
			
			// aapt resource value: 0x7f04011d
			public const int GetingData_Language_en = 2130968861;
			
			// aapt resource value: 0x7f040045
			public const int GetingData_Language_fa = 2130968645;
			
			// aapt resource value: 0x7f0401b8
			public const int GettingUserInfo_Language_en = 2130969016;
			
			// aapt resource value: 0x7f0400cf
			public const int GettingUserInfo_Language_fa = 2130968783;
			
			// aapt resource value: 0x7f04010f
			public const int GoToHome_Language_en = 2130968847;
			
			// aapt resource value: 0x7f040023
			public const int GoToHome_Language_fa = 2130968611;
			
			// aapt resource value: 0x7f04014c
			public const int Go_Language_en = 2130968908;
			
			// aapt resource value: 0x7f040076
			public const int Go_Language_fa = 2130968694;
			
			// aapt resource value: 0x7f040103
			public const int GroupList_Language_en = 2130968835;
			
			// aapt resource value: 0x7f040017
			public const int GroupList_Language_fa = 2130968599;
			
			// aapt resource value: 0x7f04010d
			public const int GroupManager_Language_en = 2130968845;
			
			// aapt resource value: 0x7f040021
			public const int GroupManager_Language_fa = 2130968609;
			
			// aapt resource value: 0x7f0400ff
			public const int GroupName_Language_en = 2130968831;
			
			// aapt resource value: 0x7f040013
			public const int GroupName_Language_fa = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04013e
			public const int Hour_Language_en = 2130968894;
			
			// aapt resource value: 0x7f040068
			public const int Hour_Language_fa = 2130968680;
			
			// aapt resource value: 0x7f040156
			public const int InvalidAddress_Language_en = 2130968918;
			
			// aapt resource value: 0x7f040083
			public const int InvalidAddress_Language_fa = 2130968707;
			
			// aapt resource value: 0x7f0401ac
			public const int InvalidEmail_Language_en = 2130969004;
			
			// aapt resource value: 0x7f0400c3
			public const int InvalidEmail_Language_fa = 2130968771;
			
			// aapt resource value: 0x7f0401d3
			public const int InvalidUserPurchase_Language_en = 2130969043;
			
			// aapt resource value: 0x7f0400ea
			public const int InvalidUserPurchase_Language_fa = 2130968810;
			
			// aapt resource value: 0x7f040132
			public const int KB_Language_en = 2130968882;
			
			// aapt resource value: 0x7f04005c
			public const int KB_Language_fa = 2130968668;
			
			// aapt resource value: 0x7f040152
			public const int LimitSpeedTitle_Language_en = 2130968914;
			
			// aapt resource value: 0x7f04007f
			public const int LimitSpeedTitle_Language_fa = 2130968703;
			
			// aapt resource value: 0x7f040104
			public const int LinkAddressTitle_Language_en = 2130968836;
			
			// aapt resource value: 0x7f040018
			public const int LinkAddressTitle_Language_fa = 2130968600;
			
			// aapt resource value: 0x7f040148
			public const int LinkDetail_Language_en = 2130968904;
			
			// aapt resource value: 0x7f040072
			public const int LinkDetail_Language_fa = 2130968690;
			
			// aapt resource value: 0x7f04017d
			public const int LinkInvariable_Language_en = 2130968957;
			
			// aapt resource value: 0x7f04009c
			public const int LinkInvariable_Language_fa = 2130968732;
			
			// aapt resource value: 0x7f040171
			public const int Loading_Language_en = 2130968945;
			
			// aapt resource value: 0x7f040090
			public const int Loading_Language_fa = 2130968720;
			
			// aapt resource value: 0x7f04019c
			public const int LoginError_Language_en = 2130968988;
			
			// aapt resource value: 0x7f0400b3
			public const int LoginError_Language_fa = 2130968755;
			
			// aapt resource value: 0x7f04019a
			public const int LoginIn_Language_en = 2130968986;
			
			// aapt resource value: 0x7f0400b1
			public const int LoginIn_Language_fa = 2130968753;
			
			// aapt resource value: 0x7f04019b
			public const int LoginSuccess_Language_en = 2130968987;
			
			// aapt resource value: 0x7f0400b2
			public const int LoginSuccess_Language_fa = 2130968754;
			
			// aapt resource value: 0x7f040128
			public const int LoginToSharing_Language_en = 2130968872;
			
			// aapt resource value: 0x7f040050
			public const int LoginToSharing_Language_fa = 2130968656;
			
			// aapt resource value: 0x7f0401d4
			public const int LoginUserPassError_Language_en = 2130969044;
			
			// aapt resource value: 0x7f0400eb
			public const int LoginUserPassError_Language_fa = 2130968811;
			
			// aapt resource value: 0x7f0401a3
			public const int LoginUser_Language_en = 2130968995;
			
			// aapt resource value: 0x7f0400ba
			public const int LoginUser_Language_fa = 2130968762;
			
			// aapt resource value: 0x7f04019e
			public const int Login_Language_en = 2130968990;
			
			// aapt resource value: 0x7f0400b5
			public const int Login_Language_fa = 2130968757;
			
			// aapt resource value: 0x7f0401a4
			public const int LogoutUser_Language_en = 2130968996;
			
			// aapt resource value: 0x7f0400bb
			public const int LogoutUser_Language_fa = 2130968763;
			
			// aapt resource value: 0x7f040133
			public const int MB_Language_en = 2130968883;
			
			// aapt resource value: 0x7f04005d
			public const int MB_Language_fa = 2130968669;
			
			// aapt resource value: 0x7f040151
			public const int MaximumConnectionCountTitle_Language_en = 2130968913;
			
			// aapt resource value: 0x7f04007e
			public const int MaximumConnectionCountTitle_Language_fa = 2130968702;
			
			// aapt resource value: 0x7f04013d
			public const int Minute_Language_en = 2130968893;
			
			// aapt resource value: 0x7f040067
			public const int Minute_Language_fa = 2130968679;
			
			// aapt resource value: 0x7f04007b
			public const int NameValidation_Language_fa = 2130968699;
			
			// aapt resource value: 0x7f04014d
			public const int NewFolder_Language_en = 2130968909;
			
			// aapt resource value: 0x7f040077
			public const int NewFolder_Language_fa = 2130968695;
			
			// aapt resource value: 0x7f0401d6
			public const int NewName_Language_en = 2130969046;
			
			// aapt resource value: 0x7f0400ed
			public const int NewName_Language_fa = 2130968813;
			
			// aapt resource value: 0x7f040180
			public const int NoErrorFound_Language_en = 2130968960;
			
			// aapt resource value: 0x7f04009f
			public const int NoErrorFound_Language_fa = 2130968735;
			
			// aapt resource value: 0x7f0401d1
			public const int NoFileSize_Language_en = 2130969041;
			
			// aapt resource value: 0x7f0400e8
			public const int NoFileSize_Language_fa = 2130968808;
			
			// aapt resource value: 0x7f0401d7
			public const int NoName_Language_en = 2130969047;
			
			// aapt resource value: 0x7f0400ee
			public const int NoName_Language_fa = 2130968814;
			
			// aapt resource value: 0x7f040195
			public const int NoSound_Language_en = 2130968981;
			
			// aapt resource value: 0x7f04005a
			public const int NoSound_Language_fa = 2130968666;
			
			// aapt resource value: 0x7f0401d0
			public const int NoStorageFileSize_Language_en = 2130969040;
			
			// aapt resource value: 0x7f0400e7
			public const int NoStorageFileSize_Language_fa = 2130968807;
			
			// aapt resource value: 0x7f0401ce
			public const int NoStorage_Language_en = 2130969038;
			
			// aapt resource value: 0x7f0400e5
			public const int NoStorage_Language_fa = 2130968805;
			
			// aapt resource value: 0x7f040158
			public const int NoVideoFormatFound_Language_en = 2130968920;
			
			// aapt resource value: 0x7f040085
			public const int NoVideoFormatFound_Language_fa = 2130968709;
			
			// aapt resource value: 0x7f040194
			public const int NoVideo_Language_en = 2130968980;
			
			// aapt resource value: 0x7f040059
			public const int NoVideo_Language_fa = 2130968665;
			
			// aapt resource value: 0x7f0400f0
			public const int No_Language_en = 2130968816;
			
			// aapt resource value: 0x7f040004
			public const int No_Language_fa = 2130968580;
			
			// aapt resource value: 0x7f0400f1
			public const int OK_Language_en = 2130968817;
			
			// aapt resource value: 0x7f040005
			public const int OK_Language_fa = 2130968581;
			
			// aapt resource value: 0x7f040183
			public const int OpenFileLocation_Language_en = 2130968963;
			
			// aapt resource value: 0x7f040038
			public const int OpenFileLocation_Language_fa = 2130968632;
			
			// aapt resource value: 0x7f040111
			public const int OpenFile_Language_en = 2130968849;
			
			// aapt resource value: 0x7f040035
			public const int OpenFile_Language_fa = 2130968629;
			
			// aapt resource value: 0x7f04015c
			public const int Password_Language_en = 2130968924;
			
			// aapt resource value: 0x7f040089
			public const int Password_Language_fa = 2130968713;
			
			// aapt resource value: 0x7f04011c
			public const int Paused_Language_en = 2130968860;
			
			// aapt resource value: 0x7f040044
			public const int Paused_Language_fa = 2130968644;
			
			// aapt resource value: 0x7f04011b
			public const int Pausing_Language_en = 2130968859;
			
			// aapt resource value: 0x7f040043
			public const int Pausing_Language_fa = 2130968643;
			
			// aapt resource value: 0x7f040141
			public const int PerSecound_Language_en = 2130968897;
			
			// aapt resource value: 0x7f04006b
			public const int PerSecound_Language_fa = 2130968683;
			
			// aapt resource value: 0x7f040197
			public const int PermisionFirstMessage_Language_en = 2130968983;
			
			// aapt resource value: 0x7f0400ae
			public const int PermisionFirstMessage_Language_fa = 2130968750;
			
			// aapt resource value: 0x7f0400f3
			public const int Play_Language_en = 2130968819;
			
			// aapt resource value: 0x7f040007
			public const int Play_Language_fa = 2130968583;
			
			// aapt resource value: 0x7f0401cb
			public const int PleaseFillAllItems_Language_en = 2130969035;
			
			// aapt resource value: 0x7f0400e2
			public const int PleaseFillAllItems_Language_fa = 2130968802;
			
			// aapt resource value: 0x7f0401c8
			public const int QuestionDeleteFilesError_Language_en = 2130969032;
			
			// aapt resource value: 0x7f0400df
			public const int QuestionDeleteFilesError_Language_fa = 2130968799;
			
			// aapt resource value: 0x7f0401c9
			public const int QuestionServerFileUpload_Language_en = 2130969033;
			
			// aapt resource value: 0x7f0400e0
			public const int QuestionServerFileUpload_Language_fa = 2130968800;
			
			// aapt resource value: 0x7f040139
			public const int QueueManager_Language_en = 2130968889;
			
			// aapt resource value: 0x7f040063
			public const int QueueManager_Language_fa = 2130968675;
			
			// aapt resource value: 0x7f040146
			public const int Reconnect_Language_en = 2130968902;
			
			// aapt resource value: 0x7f040070
			public const int Reconnect_Language_fa = 2130968688;
			
			// aapt resource value: 0x7f0401be
			public const int RefreshListError_Language_en = 2130969022;
			
			// aapt resource value: 0x7f0400d5
			public const int RefreshListError_Language_fa = 2130968789;
			
			// aapt resource value: 0x7f0401bc
			public const int RefreshList_Language_en = 2130969020;
			
			// aapt resource value: 0x7f0400d3
			public const int RefreshList_Language_fa = 2130968787;
			
			// aapt resource value: 0x7f0401bd
			public const int Refreshing_Language_en = 2130969021;
			
			// aapt resource value: 0x7f0400d4
			public const int Refreshing_Language_fa = 2130968788;
			
			// aapt resource value: 0x7f0401a9
			public const int RegisterError_Language_en = 2130969001;
			
			// aapt resource value: 0x7f0400c0
			public const int RegisterError_Language_fa = 2130968768;
			
			// aapt resource value: 0x7f0401ab
			public const int RegisterSuccess_Language_en = 2130969003;
			
			// aapt resource value: 0x7f0400c2
			public const int RegisterSuccess_Language_fa = 2130968770;
			
			// aapt resource value: 0x7f0401a2
			public const int RegisterUser_Language_en = 2130968994;
			
			// aapt resource value: 0x7f0400b9
			public const int RegisterUser_Language_fa = 2130968761;
			
			// aapt resource value: 0x7f0401a8
			public const int Registering_Language_en = 2130969000;
			
			// aapt resource value: 0x7f0400bf
			public const int Registering_Language_fa = 2130968767;
			
			// aapt resource value: 0x7f0401d5
			public const int RenameLink_Language_en = 2130969045;
			
			// aapt resource value: 0x7f0400ec
			public const int RenameLink_Language_fa = 2130968812;
			
			// aapt resource value: 0x7f04018c
			public const int RepairLink_Language_en = 2130968972;
			
			// aapt resource value: 0x7f0400a5
			public const int RepairLink_Language_fa = 2130968741;
			
			// aapt resource value: 0x7f040130
			public const int ResolutionTitle_Language_en = 2130968880;
			
			// aapt resource value: 0x7f040058
			public const int ResolutionTitle_Language_fa = 2130968664;
			
			// aapt resource value: 0x7f040143
			public const int ResumeCapabilityTitle_Language_en = 2130968899;
			
			// aapt resource value: 0x7f04006d
			public const int ResumeCapabilityTitle_Language_fa = 2130968685;
			
			// aapt resource value: 0x7f040100
			public const int SaveAddress_Language_en = 2130968832;
			
			// aapt resource value: 0x7f040014
			public const int SaveAddress_Language_fa = 2130968596;
			
			// aapt resource value: 0x7f040154
			public const int SaveSetting_Language_en = 2130968916;
			
			// aapt resource value: 0x7f040081
			public const int SaveSetting_Language_fa = 2130968705;
			
			// aapt resource value: 0x7f04017e
			public const int SaveSuccess_Language_en = 2130968958;
			
			// aapt resource value: 0x7f04009d
			public const int SaveSuccess_Language_fa = 2130968733;
			
			// aapt resource value: 0x7f04017c
			public const int Save_Language_en = 2130968956;
			
			// aapt resource value: 0x7f04009b
			public const int Save_Language_fa = 2130968731;
			
			// aapt resource value: 0x7f04013c
			public const int Secound_Language_en = 2130968892;
			
			// aapt resource value: 0x7f040066
			public const int Secound_Language_fa = 2130968678;
			
			// aapt resource value: 0x7f0400f8
			public const int SelectAll_Language_en = 2130968824;
			
			// aapt resource value: 0x7f04000c
			public const int SelectAll_Language_fa = 2130968588;
			
			// aapt resource value: 0x7f040153
			public const int SelectLanguage_Language_en = 2130968915;
			
			// aapt resource value: 0x7f040080
			public const int SelectLanguage_Language_fa = 2130968704;
			
			// aapt resource value: 0x7f040109
			public const int Select_Language_en = 2130968841;
			
			// aapt resource value: 0x7f04001d
			public const int Select_Language_fa = 2130968605;
			
			// aapt resource value: 0x7f040114
			public const int Selectyourlink_Language_en = 2130968852;
			
			// aapt resource value: 0x7f04003c
			public const int Selectyourlink_Language_fa = 2130968636;
			
			// aapt resource value: 0x7f04016f
			public const int SendError_Language_en = 2130968943;
			
			// aapt resource value: 0x7f040034
			public const int SendError_Language_fa = 2130968628;
			
			// aapt resource value: 0x7f04016a
			public const int SendFeedBackMesage_Language_en = 2130968938;
			
			// aapt resource value: 0x7f04002f
			public const int SendFeedBackMesage_Language_fa = 2130968623;
			
			// aapt resource value: 0x7f0401c0
			public const int SendFile_Language_en = 2130969024;
			
			// aapt resource value: 0x7f0400d7
			public const int SendFile_Language_fa = 2130968791;
			
			// aapt resource value: 0x7f04016e
			public const int SendSuccess_Language_en = 2130968942;
			
			// aapt resource value: 0x7f040033
			public const int SendSuccess_Language_fa = 2130968627;
			
			// aapt resource value: 0x7f04016c
			public const int Send_Language_en = 2130968940;
			
			// aapt resource value: 0x7f040031
			public const int Send_Language_fa = 2130968625;
			
			// aapt resource value: 0x7f0401c2
			public const int SendingFileError_Language_en = 2130969026;
			
			// aapt resource value: 0x7f0400d9
			public const int SendingFileError_Language_fa = 2130968793;
			
			// aapt resource value: 0x7f0401c3
			public const int SendingFileSuccess_Language_en = 2130969027;
			
			// aapt resource value: 0x7f0400da
			public const int SendingFileSuccess_Language_fa = 2130968794;
			
			// aapt resource value: 0x7f0401c1
			public const int SendingFile_Language_en = 2130969025;
			
			// aapt resource value: 0x7f0400d8
			public const int SendingFile_Language_fa = 2130968792;
			
			// aapt resource value: 0x7f04016d
			public const int Sending_Language_en = 2130968941;
			
			// aapt resource value: 0x7f040032
			public const int Sending_Language_fa = 2130968626;
			
			// aapt resource value: 0x7f04015a
			public const int ServerAddressExample_Language_en = 2130968922;
			
			// aapt resource value: 0x7f040087
			public const int ServerAddressExample_Language_fa = 2130968711;
			
			// aapt resource value: 0x7f04019f
			public const int ServerDownloads_Language_en = 2130968991;
			
			// aapt resource value: 0x7f0400b6
			public const int ServerDownloads_Language_fa = 2130968758;
			
			// aapt resource value: 0x7f0401bb
			public const int ServerLinks_Language_en = 2130969019;
			
			// aapt resource value: 0x7f0400d2
			public const int ServerLinks_Language_fa = 2130968786;
			
			// aapt resource value: 0x7f04013a
			public const int Setting_Language_en = 2130968890;
			
			// aapt resource value: 0x7f040064
			public const int Setting_Language_fa = 2130968676;
			
			// aapt resource value: 0x7f040173
			public const int ShareFileUsing_Language_en = 2130968947;
			
			// aapt resource value: 0x7f040092
			public const int ShareFileUsing_Language_fa = 2130968722;
			
			// aapt resource value: 0x7f040172
			public const int ShareFile_Language_en = 2130968946;
			
			// aapt resource value: 0x7f040091
			public const int ShareFile_Language_fa = 2130968721;
			
			// aapt resource value: 0x7f04012b
			public const int SharingTimer_Language_en = 2130968875;
			
			// aapt resource value: 0x7f040053
			public const int SharingTimer_Language_fa = 2130968659;
			
			// aapt resource value: 0x7f040147
			public const int ShowDetail_Language_en = 2130968903;
			
			// aapt resource value: 0x7f040071
			public const int ShowDetail_Language_fa = 2130968689;
			
			// aapt resource value: 0x7f04017f
			public const int ShowLastError_Language_en = 2130968959;
			
			// aapt resource value: 0x7f04009e
			public const int ShowLastError_Language_fa = 2130968734;
			
			// aapt resource value: 0x7f0400fb
			public const int SiteTitle_Language_en = 2130968827;
			
			// aapt resource value: 0x7f04000f
			public const int SiteTitle_Language_fa = 2130968591;
			
			// aapt resource value: 0x7f0400fc
			public const int Site_Language_en = 2130968828;
			
			// aapt resource value: 0x7f040010
			public const int Site_Language_fa = 2130968592;
			
			// aapt resource value: 0x7f0401a6
			public const int SizeTitle_Language_en = 2130968998;
			
			// aapt resource value: 0x7f0400bd
			public const int SizeTitle_Language_fa = 2130968765;
			
			// aapt resource value: 0x7f040137
			public const int Size_Language_en = 2130968887;
			
			// aapt resource value: 0x7f040061
			public const int Size_Language_fa = 2130968673;
			
			// aapt resource value: 0x7f040145
			public const int SpeedTitle_Language_en = 2130968901;
			
			// aapt resource value: 0x7f04006f
			public const int SpeedTitle_Language_fa = 2130968687;
			
			// aapt resource value: 0x7f04018e
			public const int StartRepairLink_Language_en = 2130968974;
			
			// aapt resource value: 0x7f0400a7
			public const int StartRepairLink_Language_fa = 2130968743;
			
			// aapt resource value: 0x7f040142
			public const int StatusTitle_Language_en = 2130968898;
			
			// aapt resource value: 0x7f04006c
			public const int StatusTitle_Language_fa = 2130968684;
			
			// aapt resource value: 0x7f04018a
			public const int StopDownloadQueueList_Language_en = 2130968970;
			
			// aapt resource value: 0x7f0400a3
			public const int StopDownloadQueueList_Language_fa = 2130968739;
			
			// aapt resource value: 0x7f0400f6
			public const int Stop_Language_en = 2130968822;
			
			// aapt resource value: 0x7f04000a
			public const int Stop_Language_fa = 2130968586;
			
			// aapt resource value: 0x7f040117
			public const int Stoped_Language_en = 2130968855;
			
			// aapt resource value: 0x7f040040
			public const int Stoped_Language_fa = 2130968640;
			
			// aapt resource value: 0x7f0401cf
			public const int StorageBackContactMe_Language_en = 2130969039;
			
			// aapt resource value: 0x7f0400e6
			public const int StorageBackContactMe_Language_fa = 2130968806;
			
			// aapt resource value: 0x7f040193
			public const int SuccessRepairLink_Language_en = 2130968979;
			
			// aapt resource value: 0x7f0400ac
			public const int SuccessRepairLink_Language_fa = 2130968748;
			
			// aapt resource value: 0x7f040135
			public const int TB_Language_en = 2130968885;
			
			// aapt resource value: 0x7f04005f
			public const int TB_Language_fa = 2130968671;
			
			// aapt resource value: 0x7f040144
			public const int TimeRemainingTitle_Language_en = 2130968900;
			
			// aapt resource value: 0x7f04006e
			public const int TimeRemainingTitle_Language_fa = 2130968686;
			
			// aapt resource value: 0x7f04012f
			public const int TypeTitle_Language_en = 2130968879;
			
			// aapt resource value: 0x7f040057
			public const int TypeTitle_Language_fa = 2130968663;
			
			// aapt resource value: 0x7f04016b
			public const int TypeYourMessage_Language_en = 2130968939;
			
			// aapt resource value: 0x7f040030
			public const int TypeYourMessage_Language_fa = 2130968624;
			
			// aapt resource value: 0x7f04013b
			public const int Unknown_Language_en = 2130968891;
			
			// aapt resource value: 0x7f040065
			public const int Unknown_Language_fa = 2130968677;
			
			// aapt resource value: 0x7f0401bf
			public const int UploadToServer_Language_en = 2130969023;
			
			// aapt resource value: 0x7f0400d6
			public const int UploadToServer_Language_fa = 2130968790;
			
			// aapt resource value: 0x7f04012c
			public const int Uploading_Language_en = 2130968876;
			
			// aapt resource value: 0x7f040054
			public const int Uploading_Language_fa = 2130968660;
			
			// aapt resource value: 0x7f040160
			public const int UserAuthorizationDeleted_Language_en = 2130968928;
			
			// aapt resource value: 0x7f04008d
			public const int UserAuthorizationDeleted_Language_fa = 2130968717;
			
			// aapt resource value: 0x7f04015f
			public const int UserAuthorizationListTitle_Language_en = 2130968927;
			
			// aapt resource value: 0x7f04008c
			public const int UserAuthorizationListTitle_Language_fa = 2130968716;
			
			// aapt resource value: 0x7f040157
			public const int UserAuthorization_Language_en = 2130968919;
			
			// aapt resource value: 0x7f040084
			public const int UserAuthorization_Language_fa = 2130968708;
			
			// aapt resource value: 0x7f0401cc
			public const int UserNameExist_Language_en = 2130969036;
			
			// aapt resource value: 0x7f0400e3
			public const int UserNameExist_Language_fa = 2130968803;
			
			// aapt resource value: 0x7f0401a5
			public const int UserNameTitle_Language_en = 2130968997;
			
			// aapt resource value: 0x7f0400bc
			public const int UserNameTitle_Language_fa = 2130968764;
			
			// aapt resource value: 0x7f04015b
			public const int UserName_Language_en = 2130968923;
			
			// aapt resource value: 0x7f040088
			public const int UserName_Language_fa = 2130968712;
			
			// aapt resource value: 0x7f0401a1
			public const int UserPermission_Language_en = 2130968993;
			
			// aapt resource value: 0x7f0400b8
			public const int UserPermission_Language_fa = 2130968760;
			
			// aapt resource value: 0x7f040196
			public const int VIPAccount_Language_en = 2130968982;
			
			// aapt resource value: 0x7f0400ad
			public const int VIPAccount_Language_fa = 2130968749;
			
			// aapt resource value: 0x7f0400fd
			public const int Version_Language_en = 2130968829;
			
			// aapt resource value: 0x7f040011
			public const int Version_Language_fa = 2130968593;
			
			// aapt resource value: 0x7f040108
			public const int VideoFormatTitle_Language_en = 2130968840;
			
			// aapt resource value: 0x7f04001c
			public const int VideoFormatTitle_Language_fa = 2130968604;
			
			// aapt resource value: 0x7f04012d
			public const int WaitForTick_Language_en = 2130968877;
			
			// aapt resource value: 0x7f040055
			public const int WaitForTick_Language_fa = 2130968661;
			
			// aapt resource value: 0x7f040125
			public const int Waiting_Language_en = 2130968869;
			
			// aapt resource value: 0x7f04004d
			public const int Waiting_Language_fa = 2130968653;
			
			// aapt resource value: 0x7f040185
			public const int WariningYourLinkNotSupportResumable_Language_en = 2130968965;
			
			// aapt resource value: 0x7f040026
			public const int WariningYourLinkNotSupportResumable_Language_fa = 2130968614;
			
			// aapt resource value: 0x7f0400ef
			public const int Yes_Language_en = 2130968815;
			
			// aapt resource value: 0x7f040003
			public const int Yes_Language_fa = 2130968579;
			
			// aapt resource value: 0x7f040186
			public const int YourLinkNotSupportResumable_Language_en = 2130968966;
			
			// aapt resource value: 0x7f040027
			public const int YourLinkNotSupportResumable_Language_fa = 2130968615;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f0401ad
			public const int buystorage100mb_Language_en = 2130969005;
			
			// aapt resource value: 0x7f0400c4
			public const int buystorage100mb_Language_fa = 2130968772;
			
			// aapt resource value: 0x7f0401b2
			public const int buystorage10gb_Language_en = 2130969010;
			
			// aapt resource value: 0x7f0400c9
			public const int buystorage10gb_Language_fa = 2130968777;
			
			// aapt resource value: 0x7f0401af
			public const int buystorage1gb_Language_en = 2130969007;
			
			// aapt resource value: 0x7f0400c6
			public const int buystorage1gb_Language_fa = 2130968774;
			
			// aapt resource value: 0x7f0401b3
			public const int buystorage20gb_Language_en = 2130969011;
			
			// aapt resource value: 0x7f0400ca
			public const int buystorage20gb_Language_fa = 2130968778;
			
			// aapt resource value: 0x7f0401b0
			public const int buystorage2gb_Language_en = 2130969008;
			
			// aapt resource value: 0x7f0400c7
			public const int buystorage2gb_Language_fa = 2130968775;
			
			// aapt resource value: 0x7f0401ae
			public const int buystorage500mb_Language_en = 2130969006;
			
			// aapt resource value: 0x7f0400c5
			public const int buystorage500mb_Language_fa = 2130968773;
			
			// aapt resource value: 0x7f0401b1
			public const int buystorage5gb_Language_en = 2130969009;
			
			// aapt resource value: 0x7f0400c8
			public const int buystorage5gb_Language_fa = 2130968776;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
