#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidSizeGenerator.Resource", IsApplication=true)]

namespace AndroidSizeGenerator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class CustomTitle
		{
			
			// aapt resource value: 0x7f080000
			public const int LinearLayoutRightToLeft = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int customtitlebar = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int icon = 2131230721;
			
			static CustomTitle()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private CustomTitle()
			{
			}
		}
		
		public partial class DialogResultButtons
		{
			
			// aapt resource value: 0x7f090001
			public const int ContentLayout = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int MainLayout = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int btnCancel = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int btnNo = 2131296260;
			
			// aapt resource value: 0x7f090003
			public const int btnOK = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int linearLayoutReverse = 2131296258;
			
			static DialogResultButtons()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private DialogResultButtons()
			{
			}
		}
		
		public partial class FolderBrowserDialog
		{
			
			// aapt resource value: 0x7f0a0000
			public const int LinearLayoutReverce1 = 2131361792;
			
			// aapt resource value: 0x7f0a0004
			public const int LinearLayoutReverce2 = 2131361796;
			
			// aapt resource value: 0x7f0a0007
			public const int btnBack = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int btnCancel = 2131361800;
			
			// aapt resource value: 0x7f0a0002
			public const int btnGo = 2131361794;
			
			// aapt resource value: 0x7f0a0006
			public const int btnNewFolder = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int btnSelect = 2131361797;
			
			// aapt resource value: 0x7f0a0003
			public const int mainGridView = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int txt_GoPath = 2131361793;
			
			static FolderBrowserDialog()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private FolderBrowserDialog()
			{
			}
		}
		
		public partial class FolderInfoItem
		{
			
			// aapt resource value: 0x7f0b0000
			public const int imgIcon = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int txtName = 2131427329;
			
			static FolderInfoItem()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private FolderInfoItem()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040006
			public const int LinkAddressForeground = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int LinkStateForeground = 2130968581;
			
			// aapt resource value: 0x7f04000e
			public const int NumericUpDownTextBackground = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int NumericUpDownTextForeground = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int NumericUpDownTextSelectedBackground = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int NumericUpDownTextSelectedForeground = 2130968592;
			
			// aapt resource value: 0x7f040007
			public const int ProgressCompleteBackground = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ProgressDownloadingBackground = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ProgressErrorBackground = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int ProgressNotStartedBackground = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int ProgressQueueBackground = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int ProgressStopedBackground = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int SelectedBackground = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int darkForeground = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int foreground = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int line = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int white = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050009
			public const int ButtonPaddingLeft = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ButtonPaddingRight = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int ButtonTextSize = 2131034116;
			
			// aapt resource value: 0x7f050013
			public const int CheckBoxButtonHeight = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int LinkInfoToolBoxButtonHeight = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int LinkInfoToolBoxButtonWidth = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int MenuItemHeight = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int MenuItemTextSize = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int NumericUpDownLayoutHeight = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int NumericUpDownTextHeight = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int NumericUpDownTextSize = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int NumericUpDownWidth = 2131034130;
			
			// aapt resource value: 0x7f050003
			public const int TaskInfoTextSize = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int TextBoxMinHeight = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int TextViewTextSize = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int TitleBarIconSize = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int TitleBarTextSize = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int folderLayoutHeight = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int folderSize = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int folderTextSize = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AddLink_toolbar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AgrinSplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Alert_toolbar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CancelButtonShape = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int checkIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CycleBackground = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int DeleteIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int DeleteQueueTime = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int EditBoxShape = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int IconSplashScreen = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int LinkInfoToolboxBackground = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ListLinks_toolbar = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int menuItemSelector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Mydocumentsicon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int NormalButtonShape = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int NoticeInfoSelector = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int numberCycleIcon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int NumericUpDownMainBackground = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int other_menu = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int overFlowMenu = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int PauseIcon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int PlayIcon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int PlayQueueTime = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ProgressBarShape_Complete = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ProgressBarShape_Downloading = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ProgressBarShape_Error = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ProgressBarShape_NotStarted = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ProgressBarShape_Queue = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ProgressBarShape_Stoped = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int RadioButton_Background = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int RadioShapeBorder = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int RadioShapeToggle = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ReconnectTimerBackground = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int red_scrubber_control = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int red_scrubber_control_disabled_holo = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int red_scrubber_control_focused_holo = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int red_scrubber_control_normal_holo = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int red_scrubber_control_pressed_holo = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int red_scrubber_primary_holo = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int red_scrubber_progress = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int red_scrubber_secondary_holo = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int red_scrubber_track_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int SeekBarDrawable = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int SeekBarThumb = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int seekbarThumbBackgroundImage = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int seekbarThumbImage = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int seekbarThumbProgressImage = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int SelectedListItemBackground = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int selector = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int settings_toolbar = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int shadow = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int smallIcon = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int splashscreen = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int StopQueueTime = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int TaskInfoItemBackgroundSelector = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int TaskManagerBlueBackground = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int TaskManagerGreenBackground = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int TaskManagerVioletBackground = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ToggleButtonShapeBackground = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ToolbarBackground = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ToolboxButtonBackground = 2130837566;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0001
			public const int MyButton = 2131492865;
			
			// aapt resource value: 0x7f0c0000
			public const int mainLayout = 2131492864;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomTitle = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DialogResultButtons = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FolderBrowserDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FolderInfoItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070005
			public const int MenuTextView = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int ProgressBar = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int RadioButton = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int TextView = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int TextView_LinkInfoItem = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int TextView_TaskInfoItem = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int Theme_IconSplash = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int ToggleButton = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int btn_stand = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int editText = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
