
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.ToggleAction Action;
		
		private global::Gtk.Action addLinkButton;
		
		private global::Gtk.Action PlayLinkButton;
		
		private global::Gtk.Action pauseLinksButton;
		
		private global::Gtk.Action deleteLinksButton;
		
		private global::Gtk.Action refreshLinksButton;
		
		private global::Gtk.ToggleAction btnContactUS;
		
		private global::Gtk.Action btnOpenSite;
		
		private global::Gtk.Action btnAbout;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Agrin.Mono.UI.AgrinToolbar agrintoolbar1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Agrin.Mono.UI.LinksList linkslist1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Agrin.Mono.UI.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.Action = new global::Gtk.ToggleAction ("Action", global::Mono.Unix.Catalog.GetString ("فایل"), null, null);
			this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("rferf");
			w1.Add (this.Action, null);
			this.addLinkButton = new global::Gtk.Action ("addLinkButton", null, global::Mono.Unix.Catalog.GetString ("درج لینک"), "addIcon");
			w1.Add (this.addLinkButton, null);
			this.PlayLinkButton = new global::Gtk.Action ("PlayLinkButton", null, global::Mono.Unix.Catalog.GetString ("شروع انتخاب شده ها"), "PlayIcon");
			w1.Add (this.PlayLinkButton, null);
			this.pauseLinksButton = new global::Gtk.Action ("pauseLinksButton", null, global::Mono.Unix.Catalog.GetString ("توقف انتخاب شده ها"), "pause");
			w1.Add (this.pauseLinksButton, null);
			this.deleteLinksButton = new global::Gtk.Action ("deleteLinksButton", null, global::Mono.Unix.Catalog.GetString ("حذف انتخاب شده ها"), "trash");
			w1.Add (this.deleteLinksButton, null);
			this.refreshLinksButton = new global::Gtk.Action ("refreshLinksButton", null, global::Mono.Unix.Catalog.GetString ("سعی مجدد"), "refresh");
			w1.Add (this.refreshLinksButton, null);
			this.btnContactUS = new global::Gtk.ToggleAction ("btnContactUS", global::Mono.Unix.Catalog.GetString ("تماس با ما"), null, null);
			this.btnContactUS.ShortLabel = global::Mono.Unix.Catalog.GetString ("تماس با ما...");
			w1.Add (this.btnContactUS, null);
			this.btnOpenSite = new global::Gtk.Action ("btnOpenSite", global::Mono.Unix.Catalog.GetString ("ورود به سایت"), null, null);
			this.btnOpenSite.ShortLabel = global::Mono.Unix.Catalog.GetString ("ورود به سایت...");
			w1.Add (this.btnOpenSite, null);
			this.btnAbout = new global::Gtk.Action ("btnAbout", global::Mono.Unix.Catalog.GetString ("درباره ی ما"), null, null);
			this.btnAbout.ShortLabel = global::Mono.Unix.Catalog.GetString ("درباره ی ما");
			w1.Add (this.btnAbout, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Agrin.Mono.UI.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Agrin Download Manager");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Agrin.Mono.UI.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'/></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.agrintoolbar1 = new global::Agrin.Mono.UI.AgrinToolbar ();
			this.agrintoolbar1.HeightRequest = 32;
			this.agrintoolbar1.Events = ((global::Gdk.EventMask)(256));
			this.agrintoolbar1.Name = "agrintoolbar1";
			this.vbox1.Add (this.agrintoolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.agrintoolbar1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.linkslist1 = new global::Agrin.Mono.UI.LinksList ();
			this.linkslist1.Events = ((global::Gdk.EventMask)(256));
			this.linkslist1.Name = "linkslist1";
			this.hbox2.Add (this.linkslist1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.linkslist1]));
			w4.Position = 0;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w5.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 889;
			this.DefaultHeight = 466;
			this.Show ();
		}
	}
}
