
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class AgrinToolbar
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action btnAdd;
		
		private global::Gtk.Action btnPlay;
		
		private global::Gtk.Action btnPause;
		
		private global::Gtk.Action btnRefresh;
		
		private global::Gtk.Action btnTrash;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Toolbar toolbar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Agrin.Mono.UI.AgrinToolbar
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.btnAdd = new global::Gtk.Action ("btnAdd", null, null, "addIcon");
			w2.Add (this.btnAdd, null);
			this.btnPlay = new global::Gtk.Action ("btnPlay", null, null, "PlayIcon");
			w2.Add (this.btnPlay, null);
			this.btnPause = new global::Gtk.Action ("btnPause", null, null, "pause");
			w2.Add (this.btnPause, null);
			this.btnRefresh = new global::Gtk.Action ("btnRefresh", null, null, "refresh");
			w2.Add (this.btnRefresh, null);
			this.btnTrash = new global::Gtk.Action ("btnTrash", null, null, "trash");
			w2.Add (this.btnTrash, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.HeightRequest = 32;
			this.Name = "Agrin.Mono.UI.AgrinToolbar";
			// Container child Agrin.Mono.UI.AgrinToolbar.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.HeightRequest = 24;
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><toolbar name='toolbar'><toolitem name='btnAdd' action='btnAdd'/><toolitem name='btnPlay' action='btnPlay'/><toolitem name='btnPause' action='btnPause'/><toolitem name='btnRefresh' action='btnRefresh'/><toolitem name='btnTrash' action='btnTrash'/></toolbar></ui>");
			this.toolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar")));
			this.toolbar.Name = "toolbar";
			this.toolbar.ShowArrow = false;
			this.hbox1.Add (this.toolbar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toolbar]));
			w3.Position = 0;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.btnAdd.Activated += new global::System.EventHandler (this.OnBtnAddActivated);
			this.btnPlay.Activated += new global::System.EventHandler (this.OnBtnPlayActivated);
			this.btnPause.Activated += new global::System.EventHandler (this.OnBtnPauseActivated);
			this.btnRefresh.Activated += new global::System.EventHandler (this.OnBtnRefreshActivated);
			this.btnTrash.Activated += new global::System.EventHandler (this.OnBtnTrashActivated);
		}
	}
}
