//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Agrin.MonoRapidService.RapidBazUsersService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="apiusersBinding", Namespace="urn:WSDLapiusers")]
    public partial class WSDLapiusersService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback @__constructOperationCompleted;
        
        private System.Threading.SendOrPostCallback uptimeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSDLapiusersService() {
            this.Url = "http://rrm.rapidbaz.com/api/users/operate";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogoutCompletedEventHandler LogoutCompleted;
        
        /// <remarks/>
        public event UserInfoCompletedEventHandler UserInfoCompleted;
        
        /// <remarks/>
        public event @__constructCompletedEventHandler @__constructCompleted;
        
        /// <remarks/>
        public event uptimeCompletedEventHandler uptimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:apiusersAction", RequestNamespace="urn:WSDLapiusers", ResponseNamespace="urn:WSDLapiusers")]
        [return: System.Xml.Serialization.SoapElementAttribute("LoginReturn")]
        public string Login(string user, string pass, string key, string system, string hours) {
            object[] results = this.Invoke("Login", new object[] {
                        user,
                        pass,
                        key,
                        system,
                        hours});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string user, string pass, string key, string system, string hours) {
            this.LoginAsync(user, pass, key, system, hours, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string user, string pass, string key, string system, string hours, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        user,
                        pass,
                        key,
                        system,
                        hours}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:apiusersAction", RequestNamespace="urn:WSDLapiusers", ResponseNamespace="urn:WSDLapiusers")]
        [return: System.Xml.Serialization.SoapElementAttribute("LogoutReturn")]
        public string Logout(string session) {
            object[] results = this.Invoke("Logout", new object[] {
                        session});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LogoutAsync(string session) {
            this.LogoutAsync(session, null);
        }
        
        /// <remarks/>
        public void LogoutAsync(string session, object userState) {
            if ((this.LogoutOperationCompleted == null)) {
                this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
            }
            this.InvokeAsync("Logout", new object[] {
                        session}, this.LogoutOperationCompleted, userState);
        }
        
        private void OnLogoutOperationCompleted(object arg) {
            if ((this.LogoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:apiusersAction", RequestNamespace="urn:WSDLapiusers", ResponseNamespace="urn:WSDLapiusers")]
        [return: System.Xml.Serialization.SoapElementAttribute("UserInfoReturn")]
        public string UserInfo(string session1) {
            object[] results = this.Invoke("UserInfo", new object[] {
                        session1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserInfoAsync(string session1) {
            this.UserInfoAsync(session1, null);
        }
        
        /// <remarks/>
        public void UserInfoAsync(string session1, object userState) {
            if ((this.UserInfoOperationCompleted == null)) {
                this.UserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserInfoOperationCompleted);
            }
            this.InvokeAsync("UserInfo", new object[] {
                        session1}, this.UserInfoOperationCompleted, userState);
        }
        
        private void OnUserInfoOperationCompleted(object arg) {
            if ((this.UserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserInfoCompleted(this, new UserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:apiusersAction", RequestNamespace="urn:WSDLapiusers", ResponseNamespace="urn:WSDLapiusers")]
        [return: System.Xml.Serialization.SoapElementAttribute("__constructReturn", DataType="integer")]
        public string @__construct(string x1) {
            object[] results = this.Invoke("__construct", new object[] {
                        x1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void @__constructAsync(string x1) {
            this.@__constructAsync(x1, null);
        }
        
        /// <remarks/>
        public void @__constructAsync(string x1, object userState) {
            if ((this.@__constructOperationCompleted == null)) {
                this.@__constructOperationCompleted = new System.Threading.SendOrPostCallback(this.On__constructOperationCompleted);
            }
            this.InvokeAsync("__construct", new object[] {
                        x1}, this.@__constructOperationCompleted, userState);
        }
        
        private void On__constructOperationCompleted(object arg) {
            if ((this.@__constructCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.@__constructCompleted(this, new @__constructCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:apiusersAction", RequestNamespace="urn:WSDLapiusers", ResponseNamespace="urn:WSDLapiusers")]
        [return: System.Xml.Serialization.SoapElementAttribute("uptimeReturn")]
        public string uptime() {
            object[] results = this.Invoke("uptime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uptimeAsync() {
            this.uptimeAsync(null);
        }
        
        /// <remarks/>
        public void uptimeAsync(object userState) {
            if ((this.uptimeOperationCompleted == null)) {
                this.uptimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuptimeOperationCompleted);
            }
            this.InvokeAsync("uptime", new object[0], this.uptimeOperationCompleted, userState);
        }
        
        private void OnuptimeOperationCompleted(object arg) {
            if ((this.uptimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uptimeCompleted(this, new uptimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UserInfoCompletedEventHandler(object sender, UserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void @__constructCompletedEventHandler(object sender, @__constructCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class @__constructCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal @__constructCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void uptimeCompletedEventHandler(object sender, uptimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uptimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uptimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591