
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class LinkInfoSetting
	{
		private global::Gtk.VBox vbox10;

		private global::Gtk.Notebook notebook1;

		private global::Agrin.Mono.UI.GeneralSetting generalsetting1;

		private global::Gtk.Label label10;

		private global::Agrin.Mono.UI.SpeedSetting speedsetting1;

		private global::Gtk.Label label5;

		private global::Agrin.Mono.UI.ProxySetting proxysetting1;

		private global::Gtk.Label label6;

		private global::Agrin.Mono.UI.UserAccountsSetting useraccountssetting1;

		private global::Gtk.Label label7;

		private global::Agrin.Mono.UI.LinkAddressesSetting linkaddressessetting1;

		private global::Gtk.Label label26;

		private global::Agrin.Mono.UI.LinkInfoDownloadSetting linkinfodownloadsetting1;

		private global::Gtk.Label label29;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label label30;

		private global::Gtk.CheckButton chkAllLink;

		private global::Gtk.CheckButton chkNewLink;

		private global::Gtk.HBox hbox19;

		private global::Gtk.Button btnSave;

		private global::Gtk.Button button1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Agrin.Mono.UI.LinkInfoSetting
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Agrin.Mono.UI.LinkInfoSetting";
			// Container child Agrin.Mono.UI.LinkInfoSetting.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.generalsetting1 = new global::Agrin.Mono.UI.GeneralSetting();
			this.generalsetting1.Events = ((global::Gdk.EventMask)(256));
			this.generalsetting1.Name = "generalsetting1";
			this.notebook1.Add(this.generalsetting1);
			// Notebook tab
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xpad = 20;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("جامع");
			this.notebook1.SetTabLabel(this.generalsetting1, this.label10);
			this.label10.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.speedsetting1 = new global::Agrin.Mono.UI.SpeedSetting();
			this.speedsetting1.Events = ((global::Gdk.EventMask)(256));
			this.speedsetting1.Name = "speedsetting1";
			this.notebook1.Add(this.speedsetting1);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.speedsetting1]));
			w2.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xpad = 20;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("سرعت");
			this.notebook1.SetTabLabel(this.speedsetting1, this.label5);
			this.label5.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.proxysetting1 = new global::Agrin.Mono.UI.ProxySetting();
			this.proxysetting1.Events = ((global::Gdk.EventMask)(256));
			this.proxysetting1.Name = "proxysetting1";
			this.notebook1.Add(this.proxysetting1);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.proxysetting1]));
			w3.Position = 2;
			// Notebook tab
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xpad = 20;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("پروکسی");
			this.notebook1.SetTabLabel(this.proxysetting1, this.label6);
			this.label6.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.useraccountssetting1 = new global::Agrin.Mono.UI.UserAccountsSetting();
			this.useraccountssetting1.Events = ((global::Gdk.EventMask)(256));
			this.useraccountssetting1.Name = "useraccountssetting1";
			this.useraccountssetting1.IsApplicationSetting = false;
			this.notebook1.Add(this.useraccountssetting1);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.useraccountssetting1]));
			w4.Position = 3;
			// Notebook tab
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xpad = 20;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("رابط کاربری");
			this.notebook1.SetTabLabel(this.useraccountssetting1, this.label7);
			this.label7.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.linkaddressessetting1 = new global::Agrin.Mono.UI.LinkAddressesSetting();
			this.linkaddressessetting1.Events = ((global::Gdk.EventMask)(256));
			this.linkaddressessetting1.Name = "linkaddressessetting1";
			this.linkaddressessetting1.IsEnabled = false;
			this.notebook1.Add(this.linkaddressessetting1);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.linkaddressessetting1]));
			w5.Position = 4;
			// Notebook tab
			this.label26 = new global::Gtk.Label();
			this.label26.Name = "label26";
			this.label26.Xpad = 20;
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("لینک ها");
			this.notebook1.SetTabLabel(this.linkaddressessetting1, this.label26);
			this.label26.ShowAll();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.linkinfodownloadsetting1 = new global::Agrin.Mono.UI.LinkInfoDownloadSetting();
			this.linkinfodownloadsetting1.Events = ((global::Gdk.EventMask)(256));
			this.linkinfodownloadsetting1.Name = "linkinfodownloadsetting1";
			this.notebook1.Add(this.linkinfodownloadsetting1);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.linkinfodownloadsetting1]));
			w6.Position = 5;
			// Notebook tab
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.Xpad = 20;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("دریافت و پایان");
			this.notebook1.SetTabLabel(this.linkinfodownloadsetting1, this.label29);
			this.label29.ShowAll();
			this.vbox10.Add(this.notebook1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.notebook1]));
			w7.Position = 0;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("ذخیره این تنظیمات برای ");
			this.hbox13.Add(this.label30);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label30]));
			w8.PackType = ((global::Gtk.PackType)(1));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.chkAllLink = new global::Gtk.CheckButton();
			this.chkAllLink.CanFocus = true;
			this.chkAllLink.Name = "chkAllLink";
			this.chkAllLink.Label = global::Mono.Unix.Catalog.GetString("همه لینک ها");
			this.chkAllLink.DrawIndicator = true;
			this.chkAllLink.UseUnderline = true;
			this.chkAllLink.Xalign = 1F;
			this.hbox13.Add(this.chkAllLink);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.chkAllLink]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 1;
			w9.Expand = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.chkNewLink = new global::Gtk.CheckButton();
			this.chkNewLink.CanFocus = true;
			this.chkNewLink.Name = "chkNewLink";
			this.chkNewLink.Label = global::Mono.Unix.Catalog.GetString("لینک های جدید");
			this.chkNewLink.DrawIndicator = true;
			this.chkNewLink.UseUnderline = true;
			this.chkNewLink.Xalign = 1F;
			this.hbox13.Add(this.chkNewLink);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.chkNewLink]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 2;
			w10.Expand = false;
			this.vbox10.Add(this.hbox13);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox13]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btnSave = new global::Gtk.Button();
			this.btnSave.WidthRequest = 80;
			this.btnSave.HeightRequest = 30;
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = global::Mono.Unix.Catalog.GetString("ذخیره");
			global::Gtk.Image w12 = new global::Gtk.Image();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.SmallToolbar);
			this.btnSave.Image = w12;
			this.hbox19.Add(this.btnSave);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.btnSave]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 80;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("انصراف");
			global::Gtk.Image w14 = new global::Gtk.Image();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.SmallToolbar);
			this.button1.Image = w14;
			this.hbox19.Add(this.button1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.button1]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox10.Add(this.hbox19);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox19]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.Add(this.vbox10);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
			this.btnSave.Clicked += new global::System.EventHandler(this.OnBtnSaveClicked);
		}
	}
}
