
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class GeneralSetting
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry txt_FileName;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label lbl_Size;

		private global::Gtk.Label label2;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Button btn_Path;

		private global::Gtk.Entry txt_SavePath;

		private global::Gtk.Label label3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Entry txt_Description;

		private global::Gtk.Label label4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Agrin.Mono.UI.GeneralSetting
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Agrin.Mono.UI.GeneralSetting";
			// Container child Agrin.Mono.UI.GeneralSetting.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txt_FileName = new global::Gtk.Entry();
			this.txt_FileName.CanFocus = true;
			this.txt_FileName.Name = "txt_FileName";
			this.txt_FileName.IsEditable = true;
			this.txt_FileName.InvisibleChar = '●';
			this.hbox1.Add(this.txt_FileName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.txt_FileName]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.WidthRequest = 100;
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("نام فایل:");
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.lbl_Size = new global::Gtk.Label();
			this.lbl_Size.Name = "lbl_Size";
			this.lbl_Size.Xalign = 1F;
			this.hbox2.Add(this.lbl_Size);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.lbl_Size]));
			w4.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.WidthRequest = 100;
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("حجم:");
			this.hbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btn_Path = new global::Gtk.Button();
			this.btn_Path.CanFocus = true;
			this.btn_Path.Name = "btn_Path";
			this.btn_Path.UseUnderline = true;
			global::Gtk.Image w7 = new global::Gtk.Image();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.SmallToolbar);
			this.btn_Path.Image = w7;
			this.hbox5.Add(this.btn_Path);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btn_Path]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.txt_SavePath = new global::Gtk.Entry();
			this.txt_SavePath.CanFocus = true;
			this.txt_SavePath.Name = "txt_SavePath";
			this.txt_SavePath.IsEditable = false;
			this.txt_SavePath.InvisibleChar = '●';
			this.hbox5.Add(this.txt_SavePath);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.txt_SavePath]));
			w9.Position = 1;
			this.hbox3.Add(this.hbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox5]));
			w10.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 100;
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("مسیر ذخیره:");
			this.hbox3.Add(this.label3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label3]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.txt_Description = new global::Gtk.Entry();
			this.txt_Description.CanFocus = true;
			this.txt_Description.Name = "txt_Description";
			this.txt_Description.IsEditable = true;
			this.txt_Description.InvisibleChar = '●';
			this.hbox4.Add(this.txt_Description);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.txt_Description]));
			w13.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 100;
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("توضیحات:");
			this.hbox4.Add(this.label4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label4]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btn_Path.Clicked += new global::System.EventHandler(this.OnBtnPathClicked);
		}
	}
}
