
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class LinkInfoDownloadDetail
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label lbl_address;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label5;

		private global::Gtk.Label lbl_tavaghof;

		private global::Gtk.Label label3;

		private global::Gtk.Label lbl_downloaded;

		private global::Gtk.Label label4;

		private global::Gtk.Label lbl_Speed;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tv;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Agrin.Mono.UI.LinkInfoDownloadDetail
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Agrin.Mono.UI.LinkInfoDownloadDetail";
			// Container child Agrin.Mono.UI.LinkInfoDownloadDetail.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lbl_address = new global::Gtk.Label();
			this.lbl_address.Name = "lbl_address";
			this.lbl_address.Xalign = 0F;
			this.vbox2.Add(this.lbl_address);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lbl_address]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 10;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("قابلیت توقف:");
			this.hbox1.Add(this.label5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label5]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lbl_tavaghof = new global::Gtk.Label();
			this.lbl_tavaghof.WidthRequest = 100;
			this.lbl_tavaghof.Name = "lbl_tavaghof";
			this.lbl_tavaghof.Xalign = 1F;
			this.lbl_tavaghof.LabelProp = global::Mono.Unix.Catalog.GetString("نامشخص");
			this.hbox1.Add(this.lbl_tavaghof);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lbl_tavaghof]));
			w3.PackType = ((global::Gtk.PackType)(1));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("دریافت شده:");
			this.label3.Justify = ((global::Gtk.Justification)(1));
			this.hbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lbl_downloaded = new global::Gtk.Label();
			this.lbl_downloaded.WidthRequest = 150;
			this.lbl_downloaded.Name = "lbl_downloaded";
			this.lbl_downloaded.Xalign = 1F;
			this.lbl_downloaded.LabelProp = global::Mono.Unix.Catalog.GetString("1024 گیگابایت");
			this.lbl_downloaded.Justify = ((global::Gtk.Justification)(1));
			this.hbox1.Add(this.lbl_downloaded);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lbl_downloaded]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("سرعت (بر ثانیه):");
			this.label4.Justify = ((global::Gtk.Justification)(1));
			this.hbox1.Add(this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label4]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lbl_Speed = new global::Gtk.Label();
			this.lbl_Speed.Name = "lbl_Speed";
			this.lbl_Speed.Xalign = 1F;
			this.lbl_Speed.Justify = ((global::Gtk.Justification)(1));
			this.hbox1.Add(this.lbl_Speed);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lbl_Speed]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tv = new global::Gtk.TreeView();
			this.tv.CanFocus = true;
			this.tv.Name = "tv";
			this.GtkScrolledWindow.Add(this.tv);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w10.Position = 2;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
