
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action asfasfAction;

	private global::Gtk.Action aaaaaaaaaAction;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button btn_about;

	private global::Gtk.Button btn_reportBug;

	private global::Gtk.HBox hbox1;

	private global::Agrin.Mono.UI.Toolbar toolbar1;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.VPaned vpaned1;

	private global::Agrin.Mono.UI.LinksList linkslist1;

	private global::Agrin.Mono.UI.LinkInfoDownloadDetail linkinfodownloaddetail1;

	private global::Agrin.Mono.UI.GroupsList groupslist1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.asfasfAction = new global::Gtk.Action("asfasfAction", global::Mono.Unix.Catalog.GetString("asfasf"), null, null);
		this.asfasfAction.ShortLabel = global::Mono.Unix.Catalog.GetString("asfasf");
		w1.Add(this.asfasfAction, null);
		this.aaaaaaaaaAction = new global::Gtk.Action("aaaaaaaaaAction", global::Mono.Unix.Catalog.GetString("aaaaaaaaa"), null, null);
		this.aaaaaaaaaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("aaaaaaaaa");
		w1.Add(this.aaaaaaaaaAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("مدیریت دانلود آگرین");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btn_about = new global::Gtk.Button();
		this.btn_about.CanFocus = true;
		this.btn_about.Name = "btn_about";
		this.btn_about.UseUnderline = true;
		this.btn_about.Label = global::Mono.Unix.Catalog.GetString("درباره ی ما");
		this.hbox3.Add(this.btn_about);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btn_about]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.btn_reportBug = new global::Gtk.Button();
		this.btn_reportBug.CanFocus = true;
		this.btn_reportBug.Name = "btn_reportBug";
		this.btn_reportBug.UseUnderline = true;
		this.btn_reportBug.Label = global::Mono.Unix.Catalog.GetString("ارائه نظرات و پیشنهادات");
		this.hbox3.Add(this.btn_reportBug);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btn_reportBug]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.toolbar1 = new global::Agrin.Mono.UI.Toolbar();
		this.toolbar1.Events = ((global::Gdk.EventMask)(256));
		this.toolbar1.Name = "toolbar1";
		this.hbox1.Add(this.toolbar1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.toolbar1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 709;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned1 = new global::Gtk.VPaned();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 333;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.linkslist1 = new global::Agrin.Mono.UI.LinksList();
		this.linkslist1.Events = ((global::Gdk.EventMask)(256));
		this.linkslist1.Name = "linkslist1";
		this.vpaned1.Add(this.linkslist1);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.linkslist1]));
		w6.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.linkinfodownloaddetail1 = new global::Agrin.Mono.UI.LinkInfoDownloadDetail();
		this.linkinfodownloaddetail1.Events = ((global::Gdk.EventMask)(256));
		this.linkinfodownloaddetail1.Name = "linkinfodownloaddetail1";
		this.vpaned1.Add(this.linkinfodownloaddetail1);
		this.hpaned1.Add(this.vpaned1);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vpaned1]));
		w8.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.groupslist1 = new global::Agrin.Mono.UI.GroupsList();
		this.groupslist1.WidthRequest = 150;
		this.groupslist1.Events = ((global::Gdk.EventMask)(256));
		this.groupslist1.Name = "groupslist1";
		this.hpaned1.Add(this.groupslist1);
		global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.groupslist1]));
		w9.Resize = false;
		w9.Shrink = false;
		this.hbox1.Add(this.hpaned1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hpaned1]));
		w10.Position = 1;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w11.Position = 1;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 924;
		this.DefaultHeight = 727;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btn_about.Clicked += new global::System.EventHandler(this.OnBtnAboutClicked);
		this.btn_reportBug.Clicked += new global::System.EventHandler(this.OnBtnReportBugClicked);
	}
}
