
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class SpeedSetting
	{
		private global::Gtk.HBox hbox14;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Label lblText;

		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Label label17;

		private global::Gtk.SpinButton txtConnectionCount;

		private global::Gtk.Label label19;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Label label15;

		private global::Gtk.SpinButton txtBufferSize;

		private global::Gtk.Label label18;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Label label16;

		private global::Gtk.SpinButton txtSpeed;

		private global::Gtk.CheckButton chkIsLimit;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Agrin.Mono.UI.SpeedSetting
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Agrin.Mono.UI.SpeedSetting";
			// Container child Agrin.Mono.UI.SpeedSetting.Gtk.Container+ContainerChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.lblText = new global::Gtk.Label();
			this.lblText.Name = "lblText";
			this.lblText.Xalign = 1F;
			this.lblText.Yalign = 0F;
			this.lblText.LabelProp = global::Mono.Unix.Catalog.GetString("تنظیمات این قسمت تاثیر زیادی در سرعت دانلود شما خواهد داشت. سعی کنید بسته به سرعت" +
					" اینترنت خود تنظیمات را وارد کنید برای مثال: اگر سرعت اینترنت شما دایال آپ است ت" +
					"عداد کانکشن ها را بیش از 4 وارد نکنید و حجم بافر را بیش از 1 کیلوبایت قرار ندهید" +
					".");
			this.lblText.Wrap = true;
			this.lblText.Justify = ((global::Gtk.Justification)(3));
			this.hbox18.Add(this.lblText);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.lblText]));
			w1.PackType = ((global::Gtk.PackType)(1));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.hbox14.Add(this.hbox18);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.hbox18]));
			w2.Position = 0;
			// Container child hbox14.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.WidthRequest = 100;
			this.label17.Name = "label17";
			this.hbox15.Add(this.label17);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.label17]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.txtConnectionCount = new global::Gtk.SpinButton(1D, 100D, 1D);
			this.txtConnectionCount.WidthRequest = 100;
			this.txtConnectionCount.CanFocus = true;
			this.txtConnectionCount.Name = "txtConnectionCount";
			this.txtConnectionCount.Adjustment.PageIncrement = 10D;
			this.txtConnectionCount.ClimbRate = 1D;
			this.txtConnectionCount.Numeric = true;
			this.txtConnectionCount.Value = 1D;
			this.hbox15.Add(this.txtConnectionCount);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.txtConnectionCount]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.WidthRequest = 160;
			this.label19.Name = "label19";
			this.label19.Xalign = 1F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("تعداد اتصال به سرور:");
			this.hbox15.Add(this.label19);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.label19]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox8.Add(this.hbox15);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox15]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.WidthRequest = 100;
			this.label15.Name = "label15";
			this.label15.Xalign = 1F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("کیلوبایت");
			this.hbox16.Add(this.label15);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label15]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.txtBufferSize = new global::Gtk.SpinButton(1D, 5120D, 1D);
			this.txtBufferSize.WidthRequest = 100;
			this.txtBufferSize.CanFocus = true;
			this.txtBufferSize.Name = "txtBufferSize";
			this.txtBufferSize.Adjustment.PageIncrement = 10D;
			this.txtBufferSize.ClimbRate = 1D;
			this.txtBufferSize.Numeric = true;
			this.txtBufferSize.Value = 1D;
			this.hbox16.Add(this.txtBufferSize);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.txtBufferSize]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label();
			this.label18.WidthRequest = 160;
			this.label18.Name = "label18";
			this.label18.Xalign = 1F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("حجم درخواست بافر:");
			this.hbox16.Add(this.label18);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.label18]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox8.Add(this.hbox16);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox16]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label();
			this.label16.WidthRequest = 100;
			this.label16.Name = "label16";
			this.label16.Xalign = 1F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("کیلوبایت بر ثانیه");
			this.hbox17.Add(this.label16);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.label16]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.txtSpeed = new global::Gtk.SpinButton(1D, 102400D, 1D);
			this.txtSpeed.WidthRequest = 100;
			this.txtSpeed.CanFocus = true;
			this.txtSpeed.Name = "txtSpeed";
			this.txtSpeed.Adjustment.PageIncrement = 10D;
			this.txtSpeed.ClimbRate = 1D;
			this.txtSpeed.Numeric = true;
			this.txtSpeed.Value = 1D;
			this.hbox17.Add(this.txtSpeed);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.txtSpeed]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.chkIsLimit = new global::Gtk.CheckButton();
			this.chkIsLimit.WidthRequest = 160;
			this.chkIsLimit.CanFocus = true;
			this.chkIsLimit.Name = "chkIsLimit";
			this.chkIsLimit.Label = global::Mono.Unix.Catalog.GetString("سرعت دریافت (محدود):");
			this.chkIsLimit.DrawIndicator = true;
			this.chkIsLimit.UseUnderline = true;
			this.hbox17.Add(this.chkIsLimit);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.chkIsLimit]));
			w13.Position = 2;
			w13.Expand = false;
			this.vbox8.Add(this.hbox17);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox17]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox14.Add(this.vbox8);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.vbox8]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.Add(this.hbox14);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.hbox18.SizeAllocated += new global::Gtk.SizeAllocatedHandler(this.OnHbox18SizeAllocated);
			this.chkIsLimit.Toggled += new global::System.EventHandler(this.OnChkIsLimitToggled);
		}
	}
}
