
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class LinkAddressesSetting
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Button btnAdd;

		private global::Gtk.Entry txt_address;

		private global::Gtk.Label label6;

		private global::Gtk.HBox hbox7;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Button btnCheck;

		private global::Gtk.Label label7;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label lblMessage;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tv;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Agrin.Mono.UI.LinkAddressesSetting
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Agrin.Mono.UI.LinkAddressesSetting";
			// Container child Agrin.Mono.UI.LinkAddressesSetting.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnAdd = new global::Gtk.Button();
			this.btnAdd.CanFocus = true;
			this.btnAdd.Name = "btnAdd";
			this.btnAdd.UseUnderline = true;
			global::Gtk.Image w1 = new global::Gtk.Image();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.SmallToolbar);
			this.btnAdd.Image = w1;
			this.hbox6.Add(this.btnAdd);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnAdd]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.txt_address = new global::Gtk.Entry();
			this.txt_address.CanFocus = true;
			this.txt_address.Name = "txt_address";
			this.txt_address.IsEditable = true;
			this.txt_address.InvisibleChar = '●';
			this.hbox6.Add(this.txt_address);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.txt_address]));
			w3.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 80;
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("آدرس:");
			this.hbox6.Add(this.label6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label6]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox5.Add(this.hbox6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.btnCheck = new global::Gtk.Button();
			this.btnCheck.HeightRequest = 30;
			this.btnCheck.CanFocus = true;
			this.btnCheck.Name = "btnCheck";
			this.btnCheck.UseUnderline = true;
			global::Gtk.Image w6 = new global::Gtk.Image();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.SmallToolbar);
			this.btnCheck.Image = w6;
			this.vbox2.Add(this.btnCheck);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.btnCheck]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox7.Add(this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 80;
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.hbox7.Add(this.label7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label7]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblMessage = new global::Gtk.Label();
			this.lblMessage.Name = "lblMessage";
			this.lblMessage.Xalign = 1F;
			this.lblMessage.LabelProp = global::Mono.Unix.Catalog.GetString("حتماً برای صحت سالم بودن لینک ها آنها را بازنگری کنید.لینک های مورد استفاده باید " +
					"از نظر حجم و محتوا با هم یکسان باشند.اگر لینک ها همسان نباشند فایل خراب دانلود م" +
					"ی شود.");
			this.lblMessage.Wrap = true;
			this.hbox1.Add(this.lblMessage);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblMessage]));
			w10.Position = 0;
			this.hbox7.Add(this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox1]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 2;
			this.vbox5.Add(this.hbox7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox7]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tv = new global::Gtk.TreeView();
			this.tv.CanFocus = true;
			this.tv.Name = "tv";
			this.GtkScrolledWindow.Add(this.tv);
			this.vbox5.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow]));
			w14.Position = 2;
			this.Add(this.vbox5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btnAdd.Clicked += new global::System.EventHandler(this.OnBtnAddClicked);
			this.txt_address.Changed += new global::System.EventHandler(this.OnTxtAddressChanged);
			this.btnCheck.Clicked += new global::System.EventHandler(this.OnBtnCheckClicked);
			this.hbox1.SizeAllocated += new global::Gtk.SizeAllocatedHandler(this.OnHbox1SizeAllocated);
		}
	}
}
