
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class LinkInfoDownloadSetting
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label9;

		private global::Gtk.ComboBox cboSystemEnd;

		private global::Gtk.CheckButton chkEndDownload;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label10;

		private global::Gtk.SpinButton txtErrorCount;

		private global::Gtk.CheckButton chkExtreme;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Agrin.Mono.UI.LinkInfoDownloadSetting
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Agrin.Mono.UI.LinkInfoDownloadSetting";
			// Container child Agrin.Mono.UI.LinkInfoDownloadSetting.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.WidthRequest = 80;
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("کن");
			this.hbox8.Add(this.label9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label9]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.cboSystemEnd = global::Gtk.ComboBox.NewText();
			this.cboSystemEnd.AppendText(global::Mono.Unix.Catalog.GetString("خاموش"));
			this.cboSystemEnd.AppendText(global::Mono.Unix.Catalog.GetString("خواب (Sleep)"));
			this.cboSystemEnd.AppendText(global::Mono.Unix.Catalog.GetString("دوباره راه اندازی"));
			this.cboSystemEnd.Name = "cboSystemEnd";
			this.cboSystemEnd.Active = 0;
			this.hbox8.Add(this.cboSystemEnd);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.cboSystemEnd]));
			w2.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.chkEndDownload = new global::Gtk.CheckButton();
			this.chkEndDownload.WidthRequest = 250;
			this.chkEndDownload.Sensitive = false;
			this.chkEndDownload.CanFocus = true;
			this.chkEndDownload.Name = "chkEndDownload";
			this.chkEndDownload.Label = global::Mono.Unix.Catalog.GetString("پس از پایان دانلود کامپیوتر را");
			this.chkEndDownload.DrawIndicator = true;
			this.chkEndDownload.UseUnderline = true;
			this.chkEndDownload.Xalign = 1F;
			this.hbox8.Add(this.chkEndDownload);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.chkEndDownload]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox6.Add(this.hbox8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox8]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.WidthRequest = 250;
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("دفعات سعی مجدد هنگام مواجه با خطا:");
			this.hbox9.Add(this.label10);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label10]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.txtErrorCount = new global::Gtk.SpinButton(1D, 100000D, 1D);
			this.txtErrorCount.CanFocus = true;
			this.txtErrorCount.Name = "txtErrorCount";
			this.txtErrorCount.Adjustment.PageIncrement = 10D;
			this.txtErrorCount.ClimbRate = 1D;
			this.txtErrorCount.Numeric = true;
			this.txtErrorCount.Value = 1D;
			this.hbox9.Add(this.txtErrorCount);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.txtErrorCount]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.chkExtreme = new global::Gtk.CheckButton();
			this.chkExtreme.WidthRequest = 80;
			this.chkExtreme.CanFocus = true;
			this.chkExtreme.Name = "chkExtreme";
			this.chkExtreme.Label = global::Mono.Unix.Catalog.GetString("بی نهایت");
			this.chkExtreme.DrawIndicator = true;
			this.chkExtreme.UseUnderline = true;
			this.chkExtreme.Xalign = 1F;
			this.hbox9.Add(this.chkExtreme);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.chkExtreme]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 2;
			w7.Expand = false;
			this.vbox6.Add(this.hbox9);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox9]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add(this.vbox6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.chkEndDownload.Toggled += new global::System.EventHandler(this.OnChkEndDownloadToggled);
			this.chkExtreme.Toggled += new global::System.EventHandler(this.OnChkExtremeToggled);
		}
	}
}
