
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class ReportBugs
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Entry txtName;

		private global::Gtk.Entry txt_email;

		private global::Gtk.Entry txt_subject;

		private global::Gtk.Entry txt_Text;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button btnSend;

		private global::Gtk.Label lbl_message;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Agrin.Mono.UI.ReportBugs
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Agrin.Mono.UI.ReportBugs";
			// Container child Agrin.Mono.UI.ReportBugs.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Homogeneous = true;
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.txtName = new global::Gtk.Entry();
			this.txtName.CanFocus = true;
			this.txtName.Name = "txtName";
			this.txtName.IsEditable = true;
			this.txtName.InvisibleChar = '●';
			this.vbox4.Add(this.txtName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.txtName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.txt_email = new global::Gtk.Entry();
			this.txt_email.CanFocus = true;
			this.txt_email.Name = "txt_email";
			this.txt_email.IsEditable = true;
			this.txt_email.InvisibleChar = '●';
			this.vbox4.Add(this.txt_email);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.txt_email]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.txt_subject = new global::Gtk.Entry();
			this.txt_subject.CanFocus = true;
			this.txt_subject.Name = "txt_subject";
			this.txt_subject.IsEditable = true;
			this.txt_subject.InvisibleChar = '●';
			this.vbox4.Add(this.txt_subject);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.txt_subject]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.txt_Text = new global::Gtk.Entry();
			this.txt_Text.HeightRequest = 0;
			this.txt_Text.CanFocus = true;
			this.txt_Text.Name = "txt_Text";
			this.txt_Text.IsEditable = true;
			this.txt_Text.InvisibleChar = '●';
			this.vbox4.Add(this.txt_Text);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.txt_Text]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.hbox2.Add(this.vbox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox4]));
			w5.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("نام:");
			this.vbox3.Add(this.label1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("ایمیل شما:");
			this.vbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("موضوع:");
			this.vbox3.Add(this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label3]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("متن");
			this.vbox3.Add(this.label4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label4]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox2.Add(this.vbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnSend = new global::Gtk.Button();
			this.btnSend.WidthRequest = 100;
			this.btnSend.HeightRequest = 50;
			this.btnSend.CanFocus = true;
			this.btnSend.Name = "btnSend";
			this.btnSend.UseUnderline = true;
			this.btnSend.Label = global::Mono.Unix.Catalog.GetString("ارسال");
			this.hbox3.Add(this.btnSend);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnSend]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lbl_message = new global::Gtk.Label();
			this.lbl_message.Name = "lbl_message";
			this.lbl_message.LabelProp = global::Mono.Unix.Catalog.GetString("نظرات و پیشنهادات شما برای ما ارزشمند هستند ما به پیشنهادات شما پاسخ می دهیم");
			this.hbox3.Add(this.lbl_message);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.lbl_message]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.btnSend.Clicked += new global::System.EventHandler(this.OnBtnSendClicked);
		}
	}
}
