// <auto-generated />
using System;
using Agrin.Server.DataBase.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Agrin.Server.DataBase.Migrations
{
    [DbContext(typeof(AgrinContext))]
    [Migration("20190113180338_newupdate")]
    partial class newupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Agrin.Server.DataBase.Models.CommentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Message");

                    b.Property<int?>("RequestIdeaId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RequestIdeaId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.DirectFileInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<bool>("IsComplete");

                    b.Property<int>("ServerId");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("DirectFiles");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.DirectFolderInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("DirectFolders");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.ExceptionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ErrorCode");

                    b.Property<string>("ErrorMessage");

                    b.Property<string>("ExceptionType");

                    b.Property<string>("HelpUrl");

                    b.Property<int?>("HttpErrorCode");

                    b.HasKey("Id");

                    b.ToTable("Exceptions");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.FileInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PostId");

                    b.Property<int?>("RequestIdeaId");

                    b.Property<int?>("RequestIdeaInfoId");

                    b.Property<int>("ServerId");

                    b.Property<byte>("Type");

                    b.Property<string>("Version")
                        .HasMaxLength(20);

                    b.Property<int?>("VersionNumber");

                    b.Property<int?>("VisitCardId");

                    b.Property<int?>("VisitCardInfoId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("RequestIdeaInfoId");

                    b.HasIndex("ServerId");

                    b.HasIndex("VisitCardInfoId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.LanguageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.LanguageKeyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(50);

                    b.Property<string>("Key")
                        .HasMaxLength(20);

                    b.Property<int>("LanguageId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguageKeys");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.LikeInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RequestIdeaId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RequestIdeaId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.PostCategoryInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LanguageKeyId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageKeyId");

                    b.ToTable("PostCategories");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.PostInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<DateTime>("LastUpdateDateTime");

                    b.Property<DateTime>("LastUpdateFileVersionDateTime");

                    b.Property<int?>("PostMusicId");

                    b.Property<byte>("PostType");

                    b.Property<int?>("PostVideoId");

                    b.Property<int>("UserId");

                    b.Property<long>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PostMusicId");

                    b.HasIndex("PostVideoId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.PostSoundInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("PostSounds");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.PostSubCategoryInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LanguageKeyId");

                    b.Property<int>("PostCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageKeyId");

                    b.HasIndex("PostCategoryId");

                    b.ToTable("PostSubCategories");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.PostVideoInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("PostVideoes");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.Relations.DirectFileToUserRelationInfo", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<long>("DirectFileId");

                    b.Property<byte>("AccessType");

                    b.HasKey("UserId", "DirectFileId");

                    b.HasIndex("DirectFileId");

                    b.ToTable("DirectFileToUserRelations");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.Relations.DirectFolderToUserRelationInfo", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("DirectFolderId");

                    b.Property<byte>("AccessType");

                    b.HasKey("UserId", "DirectFolderId");

                    b.HasIndex("DirectFolderId");

                    b.ToTable("DirectFolderToUserRelations");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.Relations.PostCategorySubCategoryRelationInfo", b =>
                {
                    b.Property<int>("PostSubCategoryId");

                    b.Property<int>("PostCategoryId");

                    b.HasKey("PostSubCategoryId", "PostCategoryId");

                    b.HasIndex("PostCategoryId");

                    b.ToTable("PostCategorySubCategoryRelationInfo");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.Relations.PostTagRelationInfo", b =>
                {
                    b.Property<int>("TagId");

                    b.Property<int>("PostId");

                    b.HasKey("TagId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("PostTagRelations");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.RequestIdeaInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("ErrorMessage");

                    b.Property<string>("ExceptionType");

                    b.Property<int?>("HttpErrorCode");

                    b.Property<string>("Message");

                    b.Property<string>("StackTrace");

                    b.Property<byte>("Status");

                    b.Property<string>("Title");

                    b.Property<byte>("Type");

                    b.Property<DateTime>("UpdatedDateTime");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RequestIdeas");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.ServerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Domain")
                        .HasMaxLength(50);

                    b.Property<string>("IpAddress")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.TagInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.UserConfirmHashInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<bool>("IsUsed");

                    b.Property<Guid>("RandomGuid");

                    b.Property<int>("RandomNumber");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserConfirmHashes");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.UserCreditInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int?>("FromUserId");

                    b.Property<Guid>("Key");

                    b.Property<int>("ToUserId");

                    b.Property<byte>("Type");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("ToUserId");

                    b.ToTable("UserCredits");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<long>("Credit");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Family");

                    b.Property<string>("Name");

                    b.Property<long>("RoamUploadSize");

                    b.Property<long>("StaticUploadSize");

                    b.Property<byte>("Status");

                    b.Property<int?>("TelegramUserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.UserRoleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("AccessType");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.UserSessionInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100);

                    b.Property<Guid>("FirstKey");

                    b.Property<bool>("IsActive");

                    b.Property<string>("OsName")
                        .HasMaxLength(50);

                    b.Property<string>("OsVersionName")
                        .HasMaxLength(50);

                    b.Property<string>("OsVersionNumber")
                        .HasMaxLength(15);

                    b.Property<Guid>("SecondKey");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.VisitCardInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(350);

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VisitCards");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.CommentInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.RequestIdeaInfo", "RequestIdeaInfo")
                        .WithMany("CommentInfoes")
                        .HasForeignKey("RequestIdeaId");

                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.DirectFileInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.ServerInfo", "ServerInfo")
                        .WithMany("DirectFileInfoes")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.DirectFolderInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.DirectFolderInfo", "ParentFolderInfo")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.FileInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.PostInfo", "PostInfo")
                        .WithMany("FileInfoes")
                        .HasForeignKey("PostId");

                    b.HasOne("Agrin.Server.DataBase.Models.RequestIdeaInfo")
                        .WithMany("FileInfoes")
                        .HasForeignKey("RequestIdeaInfoId");

                    b.HasOne("Agrin.Server.DataBase.Models.ServerInfo", "ServerInfo")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Agrin.Server.DataBase.Models.VisitCardInfo")
                        .WithMany("FileInfoes")
                        .HasForeignKey("VisitCardInfoId");
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.LanguageKeyInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.LanguageInfo", "LanguageInfo")
                        .WithMany("LanguageKeyInfoes")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.LikeInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.RequestIdeaInfo", "RequestIdeaInfo")
                        .WithMany("LikeInfoes")
                        .HasForeignKey("RequestIdeaId");

                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany("LikeInfoes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.PostCategoryInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.LanguageKeyInfo", "LanguageKeyInfo")
                        .WithMany("PostCategoryInfoes")
                        .HasForeignKey("LanguageKeyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.PostInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.PostCategoryInfo", "PostCategoryInfo")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Agrin.Server.DataBase.Models.PostSoundInfo", "PostMusicInfo")
                        .WithMany()
                        .HasForeignKey("PostMusicId");

                    b.HasOne("Agrin.Server.DataBase.Models.PostVideoInfo", "PostVideoInfo")
                        .WithMany()
                        .HasForeignKey("PostVideoId");

                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany("PostInfoes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.PostSubCategoryInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.LanguageKeyInfo", "LanguageKeyInfo")
                        .WithMany()
                        .HasForeignKey("LanguageKeyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Agrin.Server.DataBase.Models.PostCategoryInfo", "PostCategoryInfo")
                        .WithMany()
                        .HasForeignKey("PostCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.Relations.DirectFileToUserRelationInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.DirectFileInfo", "DirectFileInfo")
                        .WithMany("DirectFileToUserRelationInfoes")
                        .HasForeignKey("DirectFileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany("DirectFileToUserRelationInfoes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.Relations.DirectFolderToUserRelationInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.DirectFolderInfo", "DirectFolderInfo")
                        .WithMany("DirectFolderToUserRelationInfoes")
                        .HasForeignKey("DirectFolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany("DirectFolderToUserRelationInfoes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.Relations.PostCategorySubCategoryRelationInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.PostCategoryInfo", "PostCategoryInfo")
                        .WithMany("PostCategorySubCategoryRelationInfoes")
                        .HasForeignKey("PostCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Agrin.Server.DataBase.Models.PostSubCategoryInfo", "PostSubCategoryInfo")
                        .WithMany("PostCategorySubCategoryRelationInfoes")
                        .HasForeignKey("PostSubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.Relations.PostTagRelationInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.PostInfo", "PostInfo")
                        .WithMany("PostTagRelationInfoes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Agrin.Server.DataBase.Models.TagInfo", "TagInfo")
                        .WithMany("PostTagRelationInfoes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.RequestIdeaInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.UserConfirmHashInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany("UserConfirmHashInfoes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.UserCreditInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "FromUserInfo")
                        .WithMany("FromUserCreditInfoes")
                        .HasForeignKey("FromUserId");

                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "ToUserInfo")
                        .WithMany("ToUserCreditInfoes")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.UserRoleInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany("UserRoleInfoes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.UserSessionInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany("UserSessionInfoes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Agrin.Server.DataBase.Models.VisitCardInfo", b =>
                {
                    b.HasOne("Agrin.Server.DataBase.Models.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
