
// This file has been generated by the GUI designer. Do not modify.
namespace Agrin.Mono.UI
{
	public partial class ReportWindow
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Entry txt_Text;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button btnSend;
		
		private global::Gtk.Label lbl_message;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Agrin.Mono.UI.ReportWindow
			this.Name = "Agrin.Mono.UI.ReportWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ReportWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Agrin.Mono.UI.ReportWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(10));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Homogeneous = true;
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.txt_Text = new global::Gtk.Entry ();
			this.txt_Text.HeightRequest = 0;
			this.txt_Text.CanFocus = true;
			this.txt_Text.Name = "txt_Text";
			this.txt_Text.IsEditable = true;
			this.txt_Text.InvisibleChar = '●';
			this.vbox4.Add (this.txt_Text);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.txt_Text]));
			w1.Position = 3;
			w1.Expand = false;
			w1.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("متن");
			this.vbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label4]));
			w3.Position = 3;
			w3.Expand = false;
			w3.Fill = false;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w5.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnSend = new global::Gtk.Button ();
			this.btnSend.WidthRequest = 100;
			this.btnSend.HeightRequest = 50;
			this.btnSend.CanFocus = true;
			this.btnSend.Name = "btnSend";
			this.btnSend.UseUnderline = true;
			this.btnSend.Label = global::Mono.Unix.Catalog.GetString ("ارسال");
			this.hbox3.Add (this.btnSend);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnSend]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.lbl_message = new global::Gtk.Label ();
			this.lbl_message.Name = "lbl_message";
			this.lbl_message.LabelProp = global::Mono.Unix.Catalog.GetString ("نظرات و پیشنهادات شما برای ما ارزشمند هستند ما به پیشنهادات شما پاسخ می دهیم");
			this.hbox3.Add (this.lbl_message);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lbl_message]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 592;
			this.DefaultHeight = 227;
			this.Show ();
			this.btnSend.Clicked += new global::System.EventHandler (this.OnBtnSendClicked);
		}
	}
}
